// What the comparison is about, and what it is not.
//
// The shops sell to every kind of therapist: essential oils, massage tables,
// yoga mats, supplements. A Chinese-medicine clinic buys needles, moxa, cups,
// ear seeds, lamps, granules and the consumables around them, and that is the
// whole scope. A listing that lands in no category here is not stored at all.
//
// All patterns run against normaliseText() output: lower case, ASCII quotes,
// `x` between numbers. They avoid `\b`, which does not know Hebrew letters.

import type { ShopCategory } from './types.ts';

export const CATEGORY_ORDER: ShopCategory[] = [
  'tdp_lamps',
  'electro',
  'moxa',
  'cupping',
  'guasha',
  'ear_seeds',
  'needles',
  'granules',
  'formulas',
  'raw_herbs',
  'consumables',
  'accessories',
];

/** Out of scope, whatever the shop's category says. Checked first, on the name. */
export const EXCLUSIONS: RegExp[] = [
  /מיט(ה|ת|ות)\s*(טיפול|עיסוי|ספא)/u,
  /מיטת|מיטות|מזר[ןנ]|מזרו[ןנ]|table(\s|$)|couch/u,
  /יוגה|yoga|פילאטיס|pilates/u,
  /נר(ות)?\s*(ריח|אוירה|אווירה|ארומ|הופי|הופ|אוז[ןנ]|שעווה|סויה)/u,
  /ear candle|hopi/u,
  /שמ[ןנ]\s*(אתרי|בסיס|נשא|עיסוי|קוקוס|שקדים|זית|ארג[ןנ]|חוחובה|לבנדר|מרווה|לימו[ןנ]|תפוז|מנטה|נענע|אקליפטוס|קיק|קנאביס|המפ|טיפולי|ריחני)/u,
  /שמנים\s*(אתריים|אתרים|טהורים|לעיסוי|טיפוליים)|essential oil|carrier oil|massage oil|tisserand|aromatix|סינרגי|blend|בלנד/u,
  /(^|\s)קרם(ים)?(\s|$)|(^|\s)משח(ה|ת|ות)(\s|$)|סבו[ןנ]|שמפו|שעוו[הת]|(\s|^)wax|תחליב|לושן|lotion|סרום|serum|ג'ל(\s|$)|gel(\s|$)|balm|באלם|מסכת פנים|פילינג|scrub/u,
  /תוסף|ויטמי[ןנ]|מינרל|קריאטי[ןנ]|חלבו[ןנ]|אומגה|פרוביוטי|קולג[ןנ]|מגנזיום|אבץ|ברזל|כורכומי[ןנ]|ספירולינה|כלורלה|אשווגנדה|מלטוני[ןנ]|קפסולות\s*(צמחי|צמח)|whey|protein/u,
  /פרחי באך|bach flower|(\s|^)bach(\s|$)/u,
  /הומאופת|homeopath/u,
  /(^|\s)ספר(ים|י)?(\s|$)|(\s|^)books?(\s|$)|אטלס|atlas|מדריך|guide(\s|$)|dvd|כרטיסי[ותם]/u,
  /מכנס|חולצ|בגד|טוניק|כפכפ|(^|\s)נעל(יים|י|ים)?(\s|$)|גרב|חלוק|קימונו|סינר|apron|scrubs|uniform|מיקטורן|ז'קט|jacket/u,
  /כיסא|כסא|שרפרף|שולח[ןנ]|ארו[ןנ]|מדף|עגל[הת]|ספה|הדום|stool|chair|trolley|cabinet/u,
  /מתנ(ה|ות)|(\s|^)gift|מארז שי|שובר/u,
  /מכשיר עיסוי|massage gun|אקדח עיסוי|מסאז'|מעסה|עיסוי חשמלי|רולר|roller|כדור עיסוי|מקל עיסוי|foam|מזרו[ןנ] עיסוי|מכשיר לעיסוי/u,
  /אבנים חמות|hot stone|אב[ןנ] בזלת|basalt|מחמם אבנים/u,
  /טינקטור|tincture|הידרוסול|hydrosol|מי ורדים|תמצי(ת|ות)\s*(צמח|פרח|נוזלי)|extract(\s|$)/u,
  /קלפ(ים|י)(\s|$)|טארוט|tarot|אורקל/u,
  /בקבוק|צנצנת|(\s|^)jar|bottle|רולאו[ןנ]|roll-on|משפך|פיפט|מטפטף|dropper|ספריי ריק|spray bottle/u,
  /אצטו[ןנ]|acetone|גליצרי[ןנ]|glycerin|חומצ(ה|ת)|acid(\s|$)|סודה לשתייה|מלח\s*(ים|אמבט|הימלאיה)|salt/u,
  /שלד|skeleton|אנטומי|anatom|דגם\s*(גוף|שלד|עמוד|ברך|כתף|יד|רגל|אוז[ןנ])|(^|\s)מודל(\s|$)|מודל\s*(גוף|שלד|אוז[ןנ])/u,
  /פוסטר|poster|תרשים|מפת גוף|מפות|(\s|^)chart(\s|$)/u,
  /דנסיטי|density/u,
  /כרית|כריות|pillow|bolster|גליל תמיכה|cushion/u,
  /מגבת|מגבות|towel|חלוק/u,
  /סדי[ןנ]\s*(בד|כותנה|מיקרו|פלנל|סאטן|משי)|סדינ(י|ים)\s*(בד|כותנה|מיקרו|פלנל|סאטן|משי)|מיקרופייבר|microfib|פלנל|flannel|טקסטיל|ציפה|ציפית\s*בד|שמיכ|blanket|מפ(ה|ת|ות) (מיטה|טיפול)|שעוונית/u,
  /כפפות עיסוי|ליפה|loofah|ספוג|sponge/u,
  /קטורת|incense|מפזר ריח|diffuser|דיפיוזר|מבער שמ[ןנ]|oil burner/u,
  /(^|\s)תה(\s|$)|קפה|coffee|שוקולד|דבש|honey|סוכרי|ממתק|מזו[ןנ](\s|$)|food(\s|$)|סירופ מייפל|קמח/u,
  /(\s|^)תיק(\s|$)|(\s|^)bag(\s|$)|תרמיל|נרתיק|pouch(\s|$)/u,
  /תכשיט|שרשרת|צמיד|טבעת|עגיל/u,
  /איפור|makeup|cosmetic|קוסמטי|דאודורנט|deodorant|בושם|perfume|parfum|לק(\s|$)|מסקרה/u,
  /מטהר אוויר|air purifier|מכשיר אדים|humidifier|מאוורר|מפזר/u,
  /shiatsu|שיאצו|מזרן שיאצו/u,
  /דיקור קוסמטי|microneedl|דרמרולר|דרמה רולר|derma/u,
  /פדיקור|pedicure|מניקור|manicure|רגלית/u,
  /שטיח|חגור(ה|ת)|acupressure\s*mat|(^|\s)mat(\s|$)/u,
  /(^|\s)מפ(ה|ת|ות)(\s|$)|(^|\s)maps?(\s|$)/u,
  /צטיל|cetyl|סטארי[לק]|stearyl|stearic/u,
  /בזלת/u,
  /ערכ(ה|ת)\s*ל(קורס|הכנת|עיסוי)|נר(ות)?\s*\d+\s*שעות/u,
  /ניקוי רעלים|detox/u,
  /כפפ(ה|ת|ות)\s*(עיסוי|לעיסוי|כדורים|קרצוף)|לעיסוי(\s|$)|קרצוף/u,
  /לכדורים|pill\s*box|קופסת כדורים|כוס(ית)?\s*מדידה|measuring cup|שפדל|spatula|גביע/u,
];

/**
 * Out of scope with no appeal: no rescue word brings these back. Cetyl
 * alcohol is a cosmetic raw material however much "alcohol" it contains.
 */
export const HARD_EXCLUSIONS: RegExp[] = [
  /צטיל|cetyl|סטארי[לק]|stearyl|stearic|בנזיל|benzyl/u,
  /פדיקור|pedicure|מניקור|manicure|רגלית/u,
  /שטיח|חגור(ה|ת)|acupressure\s*mat|(^|\s)mat(\s|$)/u,
  /(^|\s)מודל(\s|$)|מודל\s*(גוף|שלד|אוז[ןנ])|דגם\s*(גוף|שלד|אוז[ןנ])/u,
  /(^|\s)ספר(ים|י)?(\s|$)|(\s|^)books?(\s|$)/u,
];

/**
 * Names that stay in scope even when an exclusion matches them: a bottle of
 * alcohol is a consumable, not a bottle; a moxa burner is not an oil burner.
 */
export const RESCUES: RegExp[] = [
  /אלכוהול|alcohol/u,
  /מחט|needle/u,
  /כוסות\s*רוח|cupping/u,
  /tdp/u,
  /מוקס|moxa/u,
  /גרנול|granul/u,
  /אל[\s-]*בד|אלבד|non[\s-]*woven|חד[\s-]*פעמי|disposable|ניילון|nylon|נייר|paper|גליל\s*סדי[ןנ]/u,
  /גו+א?ו?א?ה?\s*-?\s*שה|gua\s*-?\s*sha|guasha/u,
  /זרעי\s*מגנט|גאוס|gauss/u,
];

/**
 * The shops' own category names, mapped. A category mapped to null is out of
 * scope for every item in it; a category missing here decides nothing and the
 * name rules take over. Filled from what each shop listed on 2026-09-11.
 */
export const STORE_CATEGORY_MAP: Record<string, Record<string, ShopCategory | null>> = {
  medicinebom: {
    'מחטים קוראניות Dong Bang': 'needles',
    'מחטים לדיקור יבש': 'needles',
    'מחטים סיניות Golden needle': 'needles',
    'נעצים/מחטים תת עוריות/פנצטות': 'needles',
    'מחטי TONY': 'needles',
    'מחטי Seirin יפניות מקוריות': 'needles',
    'ציוד לטיפול דרך האוזן': 'ear_seeds',
    'רפואה אוריקולרית': 'ear_seeds',
    'מוקסות כוורת': 'moxa',
    'מקלות מוקסה': 'moxa',
    'מוקסות בתפזורת': 'moxa',
    'כוסות רוח': 'cupping',
    'מנורת חימום': 'tdp_lamps',
    גרנולות: 'ear_seeds',
    מגנטים: 'ear_seeds',
    'ציוד נלווה לטיפולי דיקור': 'accessories',
    'מוצרים חיוניים לקליניקה': 'consumables',
    'אלקטרו/TENS': 'electro',
    'קופסאות וערכות מוקסה': 'moxa',
    'מכשירי טייגר וליון וורמר': 'moxa',
    'מוקסות על מחט': 'moxa',
    "ציוד לסוז'וק": 'needles',
    'מאתרים ומוצרים לטיפול מרידאני': 'accessories',
    'מפות ומודלים': null,
    'בקבוקים וצנצנות': null,
    'כירופרקטיקה ופיזיולוגיה': null,
    'סדינים וכיסויים למיטות': 'consumables',
    'מכשירי לייזר': 'electro',
    'שמני בסיס וקרמים טיפוליים': null,
    'TISSERAND - שמנים אתרים טהורים ואיכותיים': null,
    'שמנים אתרים מקצועיים למטפלים- AROMATIX': null,
    'מיטות טיפולים ועיסוי': null,
    "מכשירי עיסוי ( מסאג' )ביתיים": null,
    'ספרות מקצועית': null,
    'ספרים נבחרים - מבצע חיסול': null,
    'תמציות פרחי באך': null,
    'ויטמינים מינרלים וצמחים': null,
    'ברא צמחים - תוספי תזונה ותמציות': null,
    'מוצרי אווירה ומתנות': null,
    'כריות גליל לטיפול, כריות סובה וכריות חימום': null,
    'אומגה גליל': null,
    נשים: null,
    '40 פלוס': null,
    'ציוד טיפולי לאוזן ונרות הופי': null,
  },
  tevadirect: {
    מחטים: 'needles',
    'מחטי דיקור נחושת': 'needles',
    'מחטי סיליקון 100': 'needles',
    'מחטי סיליקון 500': 'needles',
    'מחטים להקזת דם': 'needles',
    'סו ג וק': 'needles',
    'מחטי לחיצה עם פלסטר': 'needles',
    'מחטים לאוזן Sedatelec - ASP': 'ear_seeds',
    'דיקור אוזן': 'ear_seeds',
    "אינג'קטורים ועפרונות": 'ear_seeds',
    'גרנולה Granule': 'ear_seeds',
    מגנטים: 'ear_seeds',
    מוקסה: 'moxa',
    'כוסות רוח': 'cupping',
    'מוצרי נייר, בד ואל בד': 'consumables',
    'פלסטרים טיפוליים': 'consumables',
    'פלסטר למגנטים': 'consumables',
    'שטיח דיקור': null,
    ספרות: null,
    כוסית: null,
    'גביע פלסטיק': null,
    'בקבוק זכוכיות חום': null,
    'בקבוק פלסטיק': null,
    'צנצנת זכוכית': null,
    'צנצנת פלסטיק': null,
    'טפי (מזלף)': null,
    'גריקן פלסטיק': null,
    'מארז פלסטיק לכדורים': null,
    'שמנים צמחיים': null,
    'חמאות עיסוי': null,
    'חמאת שיאה': null,
    'ויטמין E': null,
    TMRG: null,
    'נטורל סין': null,
    דרורת: null,
    'משחות אסתר': null,
    'oils&herbs': null,
    'הלוחש לדבורים - מוצרי כוורת': null,
    מיביום: null,
    סובה: null,
    ליפה: null,
    דבש: null,
    'סבונים טבעיים': null,
    'חומרי גלם': null,
    'תוספי תזונה': null,
    'תערובות שמנים ובלנדים': null,
    'שמנים אתריים': null,
    'משחות וקרמים': null,
    'מיטות טיפולים': null,
    'מוצרי אווירה': null,
    'מוצרי עיסוי': null,
    'ציוד לספא ועיסוי': null,
    חמקרית: null,
    מפות: null,
    כריות: null,
    'דגמי שלד וחלקי גוף': null,
    דנסיטי: null,
    'סופר חוסן': null,
    'טינקטורה רז': null,
    הידרוסולים: null,
    'נרות הופי': null,
    סיקורה: null,
    פקק: null,
  },
  dryang: {
    'סדינים חד פעמיים': 'consumables',
    מוקסות: 'moxa',
    'כוסות רוח': 'cupping',
    'מחטים לדיקור': 'needles',
    פיזיותראפיה: null,
    'מיטות וציוד לקוסמטיקה': null,
    'מזרוני שיאצו': null,
    'מוצרי עיסוי חשמליים': null,
    'מזרוני ספורט': null,
    'מיטות עיסוי מאלומיניום': null,
    'נרות עיסוי': null,
    'נרות הופי': null,
    'שמני בסיס': null,
    'בקבוקים וצנצנות': null,
    'אבנים חמות ומוצרי חימום': null,
    'שמנים אתריים': null,
    'בגדי טיפול': null,
    'אביזרים ומכשור לעיסוי': null,
    מתנות: null,
    כיסאות: null,
    'אביזרים למיטות טיפולים': null,
    'סדיני בד וטקסטיל': null,
    'מוצרי יוגה': null,
    'נרות אוירה ארומטים': null,
    כריות: null,
    'מיטות טיפול מעץ': null,
    'מיטות טיפולים': null,
    'מגבות ': null,
    'סבונים טבעיים וכפפות עיסוי': null,
  },
  rosamix: {
    בקבוק: null,
    בקבוקים: null,
    מיטות: null,
    ספא: null,
    גלם: null,
    גברים: null,
    'טיפוח גוף': null,
  },
};

interface NameRule {
  category: ShopCategory;
  pattern: RegExp;
}

/**
 * Name rules in the order they are tried. The consumables that other rules
 * would misread come first ("פח מחטים" is a sharps bin, not a needle); the
 * broad consumables and accessories rules come last.
 */
export const NAME_RULES: NameRule[] = [
  // Instruments first: a thermometer is not a lamp because it says "infrared".
  { category: 'accessories', pattern: /מד\s*(חום|לחץ)|thermomet|stethoscop|סטטוסקופ|פינצט|tweezer|מספר(יים|ים)(\s|$)|scissors|עיפרון|עפרון|probe|מאתר\s*(לחץ|נקודות\s*קפיצי)|קליפס|(\s|^)clip(\s|$)|מתקן\s*(ל)?(גליל|נייר)|paper\s*(roll\s*)?holder|מנורת\s*לופה|לופה|magnif|זכוכית\s*מגדלת|מקלוני\s*עץ|חוטי\s*יוניזציה|ion\s*cord|פמפינג\s*קורד|pumping\s*cord|אלקטרודות|electrodes?/u },
  { category: 'consumables', pattern: /(פח|דלי|מיכל|קונטיינר).{0,25}מחטים|sharps|מיכל\s*חד|אלכוהול|alcohol|צמר\s*גפ[ןנ]|כפפ|glove|סדי[ןנ]|(\s|^)sheets?(\s|$)|מגבו[ןנ]|wipe|חיטוי|disinfect|sanitiz|פד(ים)?\s*(אלכוהול|גזה)|גזה|gauze/u },
  { category: 'tdp_lamps', pattern: /tdp|מנור(ה|ת|ות)\s*(חימום|אינפרא|סינית|טיפול|ריפוי|תרמית|מוקסה)|infrared lamp|far infrared|מנורת ריפוי/u },
  { category: 'electro', pattern: /אלקטרו|electro|גירוי חשמלי|stimulat|מגרה עצבי|(\s|^)tens(\s|$)|(\s|^)ems(\s|$)|לייזר|laser|pointer|מכשיר דיקור|מאתר נקודות|point finder|point detector|גלאי נקודות|מכשור חשמלי/u },
  { category: 'moxa', pattern: /מוקס|moxa|לענה|artemisia|mugwort|מחמם נמר|tiger warmer/u },
  { category: 'cupping', pattern: /כוס(ות|יות|ית)?\s*(רוח|ואקום|סיליקון|זכוכית|במבוק|שאיבה|יניקה|פלסטיק|מגנט)|cupping|(\s|^)cups?(\s|$)|ואקום|vacuum|אקדח כוסות|כוסות\s*(רוח|ואקום)/u },
  { category: 'guasha', pattern: /גו+א?ו?א?ה?\s*-?\s*שה|gua\s*-?\s*sha|guasha|קר[ןנ]\s*(באפלו|תאו|בופאלו)|scrap(er|ing)|אב[ןנ] ביאן|bian stone/u },
  { category: 'ear_seeds', pattern: /זרעי\s*(אוז[ןנ]|ואקריה|מגנט)|ear\s*seeds?|vaccaria|ואקריה|נעצי\s*אוז[ןנ]|מחטי\s*אוז[ןנ]|מדבקות\s*(אוז[ןנ]|לאוז[ןנ])|auricul|אוריקול|כדורי(ות)?\s*(אוז[ןנ]|לאוז[ןנ]|מגנט)|מגנט(ים)?\s*(אוז[ןנ]|לאוז[ןנ]|זרעי|\d)|גאוס|gauss|לאוז[ןנ](\s|$)|(\s|^)אוז[ןנ](\s|$)|ear\s*(magnets?|pellets?|press)|גרנול(ות|ה)?\s*(זהב|כסף|מגנט)|(\s|^)asp(\s|$)/u },
  { category: 'needles', pattern: /מחט|needle|נעצ|intradermal|תת[\s-]*עור|dry\s*needl|acupunct|סוג'וק|סוזוק|סו\s*ז'וק|sujok|su jok|פטיש\s*(7|שבע)|plum blossom|seven star|סבן\s*סטאר|הקזה|lancet|akupunkt|(?<![\p{L}])(ל|ב|ה|ו)?דיקור(?![\p{L}])|שונישין|shonishin/u },
  { category: 'granules', pattern: /גרנול|granul/u },
  { category: 'formulas', pattern: /פורמול|formula|טבליות|tablets?(\s|$)|pills?(\s|$)|כדורים|patent|(\s|^)(tang|wan|san|pian|jiao nang)(\s|$)|קפסולות|capsul|סירופ|syrup|תמצית סינית/u },
  { category: 'raw_herbs', pattern: /צמח(י|ים)?\s*(מרפא|סיני|סיניים|רפואי)|raw\s*herbs?|dried\s*herb|(\s|^)herba(\s|$)|radix|rhizoma|fructus|(\s|^)semen(\s|$)|cortex|(\s|^)flos(\s|$)|folium|caulis|ramulus|עשבי\s*מרפא|יינפיאן|yinpian/u },
  { category: 'consumables', pattern: /cotton|פד(ים)?(\s|$)|swab|נייר|paper|אל[\s-]*בד|non[\s-]*woven|פלסטר|plaster|טייפ|(\s|^)tape(\s|$)|מסכ(ה|ות)(\s|$)|(\s|^)masks?(\s|$)|ציפית|כיסוי\s*(ראש|פנים|מיטה|לראש|לפנים)|face\s*(cradle|rest)|headrest|חד[\s-]*פעמי|disposable|גליל\s*(נייר|אל|למיטה)|תחתונים\s*חד|מגש חד/u },
  { category: 'accessories', pattern: /פינצט|tweezer|מעמד|holder|(\s|^)stand(\s|$)|מגש|tray|טיימר|timer|מכבה|extinguish|מחזיק|זכוכית מגדלת|magnif|תיק\s*(למחטים|למטפל|רופא)|מד\s*(לחץ|חום)|thermomet|stethoscop|סטטוסקופ|דופק|pulse|פטיש\s*רפלקס|reflex hammer|מטר\s*מדידה|tape measure|קליפס|clip|ערכ(ה|ת)(\s|$)|(\s|^)kit(\s|$)|(\s|^)סט(\s|$)|(\s|^)set(\s|$)|מבער|burner|כלי\s*(עזר|דיקור|טיפול)|אביזר/u },
];

/** English search terms per category, for the image script and its fallbacks. */
export const CATEGORY_TERMS: Record<ShopCategory, string> = {
  needles: 'acupuncture needles',
  moxa: 'moxa sticks moxibustion',
  cupping: 'cupping therapy cups',
  guasha: 'gua sha tool',
  ear_seeds: 'auricular ear seeds vaccaria',
  tdp_lamps: 'TDP infrared lamp',
  electro: 'electroacupuncture stimulator',
  granules: 'chinese herbal granules',
  formulas: 'chinese patent medicine pills',
  raw_herbs: 'dried chinese medicinal herbs',
  consumables: 'cotton swabs medical alcohol pads',
  accessories: 'acupuncture clinic accessories tray',
};
