/**
 * One word per concept, in Hebrew and in English, for everything the models write about
 * Chinese medicine: the catalogue writer (scripts/catalogue/write.mjs) and the library
 * chat (canon.ts). The Hebrew follows Bara's professional vocabulary (the practitioner's
 * decision, 15.9.2026); the English follows the usual clinical English. Moved here from
 * scripts/catalogue/glossary.json so the app and the scripts read one list.
 */
export interface GlossaryTerm {
  he: string;
  en: string;
}

export const TCM_GLOSSARY: readonly GlossaryTerm[] = [
  { he: "צ'י", en: "Qi" },
  { he: "דם", en: "Blood" },
  { he: "יין", en: "Yin" },
  { he: "יאנג", en: "Yang" },
  { he: "תמצית (ג'ינג)", en: "Essence (Jing)" },
  { he: "נפש (שן)", en: "Spirit (Shen)" },
  { he: "נוזלי גוף", en: "Body fluids" },
  { he: "חיצון", en: "Exterior" },
  { he: "פנים", en: "Interior" },
  { he: "חום", en: "Heat" },
  { he: "אש", en: "Fire" },
  { he: "קור", en: "Cold" },
  { he: "לחות", en: "Dampness" },
  { he: "ליחה", en: "Phlegm" },
  { he: "יובש", en: "Dryness" },
  { he: "רוח", en: "Wind" },
  { he: "רוח-קור", en: "Wind-Cold" },
  { he: "רוח-חום", en: "Wind-Heat" },
  { he: "רוח-לחות", en: "Wind-Dampness" },
  { he: "רוח פנימית", en: "Internal Wind" },
  { he: "חום קיץ", en: "Summer-Heat" },
  { he: "רעילות", en: "Toxicity" },
  { he: "חוסר", en: "Deficiency" },
  { he: "עודף", en: "Excess" },
  { he: "תקיעות", en: "Stagnation" },
  { he: "תקיעות צ'י", en: "Qi Stagnation" },
  { he: "תקיעות דם", en: "Blood Stasis" },
  { he: "תקיעות מזון", en: "Food Stagnation" },
  { he: "חום מחוסר", en: "Deficiency Heat" },
  { he: "חוסר יין", en: "Yin Deficiency" },
  { he: "חוסר יאנג", en: "Yang Deficiency" },
  { he: "חוסר צ'י", en: "Qi Deficiency" },
  { he: "חוסר דם", en: "Blood Deficiency" },
  { he: "לחות-חום", en: "Damp-Heat" },
  { he: "ליחה-חום", en: "Phlegm-Heat" },
  { he: "ליחה קרה", en: "Cold Phlegm" },
  { he: "המחמם העליון", en: "Upper Burner" },
  { he: "המחמם האמצעי", en: "Middle Burner" },
  { he: "המחמם התחתון", en: "Lower Burner" },
  { he: "ריאות", en: "Lung" },
  { he: "מעי גס", en: "Large Intestine" },
  { he: "קיבה", en: "Stomach" },
  { he: "טחול", en: "Spleen" },
  { he: "לב", en: "Heart" },
  { he: "מעי דק", en: "Small Intestine" },
  { he: "שלפוחית השתן", en: "Bladder" },
  { he: "כליות", en: "Kidney" },
  { he: "קרום הלב", en: "Pericardium" },
  { he: "סאן ג'יאו", en: "San Jiao" },
  { he: "כיס המרה", en: "Gallbladder" },
  { he: "כבד", en: "Liver" },
  { he: "רחם", en: "Uterus" },
  { he: "מרידיאן", en: "channel" },
  { he: "וויי צ'י", en: "Wei Qi" },
  { he: "יינג צ'י", en: "Ying Qi" },
  { he: "יואן צ'י", en: "Yuan Qi" },
  { he: "משחרר חיצון", en: "releases the Exterior" },
  { he: "מטהר חום", en: "clears Heat" },
  { he: "מסלק אש", en: "drains Fire" },
  { he: "מסלק רעילות", en: "relieves Toxicity" },
  { he: "מקרר דם", en: "cools the Blood" },
  { he: "מסלק לחות", en: "resolves Dampness" },
  { he: "מנקז לחות", en: "drains Dampness" },
  { he: "משתן", en: "promotes urination" },
  { he: "מסלק רוח-לחות", en: "dispels Wind-Dampness" },
  { he: "מתמיר ליחה", en: "transforms Phlegm" },
  { he: "מפסיק שיעול", en: "stops cough" },
  { he: "מרגיע צפצופים", en: "calms wheezing" },
  { he: "מניע צ'י", en: "moves Qi" },
  { he: "מווסת צ'י", en: "regulates Qi" },
  { he: "מוריד צ'י", en: "descends Qi" },
  { he: "מניע דם", en: "invigorates the Blood" },
  { he: "מפסיק דימום", en: "stops bleeding" },
  { he: "מחמם פנים", en: "warms the Interior" },
  { he: "מפזר קור", en: "disperses Cold" },
  { he: "מחזק צ'י", en: "tonifies Qi" },
  { he: "מחזק דם", en: "nourishes the Blood" },
  { he: "מחזק יאנג", en: "tonifies Yang" },
  { he: "מזין יין", en: "nourishes Yin" },
  { he: "סופח", en: "astringes" },
  { he: "מייצב חיצון", en: "consolidates the Exterior" },
  { he: "מרגיע נפש", en: "calms the Spirit" },
  { he: "פותח פתחים", en: "opens the orifices" },
  { he: "מפסיק רוח", en: "extinguishes Wind" },
  { he: "מסלק פרזיטים", en: "expels parasites" },
  { he: "מרגיע כאב", en: "alleviates pain" },
  { he: "מלחלח יובש", en: "moistens Dryness" },
  { he: "מלחלח מעיים", en: "moistens the Intestines" },
  { he: "מרוקן מטה", en: "drains downward" },
  { he: "מוציא מוגלה", en: "expels pus" },
  { he: "מפחית נפיחות", en: "reduces swelling" },
  { he: "מייזע", en: "induces sweating" },
  { he: "מרגיע את העובר", en: "calms the fetus" },
  { he: "מסדיר מחזור", en: "regulates menstruation" },
  { he: "מעלה יאנג", en: "raises Yang" },
  { he: "מהרמן", en: "harmonizes" },
  { he: "מפסיקי דימום", en: "herbs that stop bleeding" },
  { he: "מרגיעי נפש", en: "herbs that calm the Spirit" },
  { he: "מסלקי אש ורעילות", en: "herbs that clear Heat and relieve Toxicity" },
  { he: "מכווץ", en: "astringent" },
  { he: "מר", en: "bitter" },
  { he: "מתוק", en: "sweet" },
  { he: "חריף", en: "acrid" },
  { he: "חמוץ", en: "sour" },
  { he: "מלוח", en: "salty" },
  { he: "תפל", en: "bland" },
  { he: "ארומטי", en: "aromatic" },
  { he: "חם", en: "hot" },
  { he: "חמים", en: "warm" },
  { he: "מעט חמים", en: "slightly warm" },
  { he: "ניטרלי", en: "neutral" },
  { he: "קריר", en: "cool" },
  { he: "קר", en: "cold" },
  { he: "קר מאוד", en: "very cold" },
  { he: "היריון", en: "pregnancy" },
  { he: "הנקה", en: "breastfeeding" },
  { he: "התוויית נגד", en: "contraindication" },
  { he: "אינטראקציה עם תרופות", en: "drug interaction" },
  { he: "אי-התאמה", en: "incompatibility" },
  { he: "לא מאושר לשימוש בישראל", en: "not approved for use in Israel" },
  { he: "מינון יומי", en: "daily dose" },
  { he: "גרם", en: "g" },
  { he: "מ״ל", en: "ml" },
  { he: "צון", en: "cun" },
  { he: "דיקור אנכי", en: "perpendicular insertion" },
  { he: "דיקור אלכסוני", en: "oblique insertion" },
  { he: "דיקור רוחבי", en: "transverse insertion" },
  { he: "מוקסה", en: "moxibustion" },
  { he: "לשון", en: "tongue" },
  { he: "חיפוי", en: "coating" },
  { he: "דופק", en: "pulse" },
  { he: "תסמונת Bi", en: "Bi syndrome" },
  { he: "דיסמנוריאה", en: "dysmenorrhea" },
  { he: "אמנוריאה", en: "amenorrhea" },
  { he: "הזעה ספונטנית", en: "spontaneous sweating" },
  { he: "הזעות לילה", en: "night sweats" },
  { he: "פלפיטציות", en: "palpitations" },
  { he: "נדודי שינה", en: "insomnia" },
  { he: "סחרחורת", en: "dizziness" },
  { he: "טיניטוס", en: "tinnitus" },
  { he: "בצקת", en: "edema" },
  { he: "עצירות", en: "constipation" },
  { he: "שלשול", en: "diarrhea" },
  { he: "אבצס", en: "abscess" },
  { he: "פצעים שאינם מגלידים", en: "non-healing sores" },
];
