-- ============================================================================
-- Acupuncture point catalogue · the 361 points of the fourteen channels
-- ============================================================================
-- Generated together with the body diagram from one table of anatomical
-- landmarks, on a 220 x 560 canvas with the midline at x = 110. Proportions
-- follow the 7.5-head adult canon; a bilateral point is stored once on the
-- right and mirrored by the renderer.
--
-- The coordinates are schematic. They show which points a treatment used and
-- roughly where — they are not an anatomical locator and must not be used as
-- one. Clinical text is left empty on purpose and every row is flagged
-- needs_review until a practitioner confirms it.
-- ============================================================================

do $seed$
begin

-- LU · lung
perform public.catalogue_upsert_point('LU1','lung',1,'Zhong Fu','中府','Central Treasury','front',154.0,125.4,true,'upper','chest');
perform public.catalogue_upsert_point('LU2','lung',2,'Yun Men','云门','Cloud Gate','front',159.3,146.8,true,'upper','chest');
perform public.catalogue_upsert_point('LU3','lung',3,'Tian Fu','天府','Celestial Storehouse','front',164.0,168.4,true,'upper','upper_arm');
perform public.catalogue_upsert_point('LU4','lung',4,'Xia Bai','侠白','Guarding White','front',168.2,190.1,true,'upper','upper_arm');
perform public.catalogue_upsert_point('LU5','lung',5,'Chi Ze','尺泽','Cubit Marsh','front',172.4,211.8,true,'upper','elbow');
perform public.catalogue_upsert_point('LU6','lung',6,'Kong Zui','孔最','Collection Hole','front',176.7,233.4,true,'upper','forearm');
perform public.catalogue_upsert_point('LU7','lung',7,'Lie Que','列缺','Broken Sequence','front',181.1,255.0,true,'upper','forearm');
perform public.catalogue_upsert_point('LU8','lung',8,'Jing Qu','经渠','Channel Ditch','front',185.8,276.6,true,'upper','forearm');
perform public.catalogue_upsert_point('LU9','lung',9,'Tai Yuan','太渊','Great Abyss','front',190.2,298.2,true,'upper','wrist');
perform public.catalogue_upsert_point('LU10','lung',10,'Yu Ji','鱼际','Fish Border','front',193.5,320.1,true,'upper','hand');
perform public.catalogue_upsert_point('LU11','lung',11,'Shao Shang','少商','Lesser Shang','front',196.0,342.0,true,'upper','hand');
-- LI · large_intestine
perform public.catalogue_upsert_point('LI1','large_intestine',1,'Shang Yang','商阳','Shang Yang','front',198.0,342.0,true,'upper','hand');
perform public.catalogue_upsert_point('LI2','large_intestine',2,'Er Jian','二间','Second Space','front',194.5,326.9,true,'upper','hand');
perform public.catalogue_upsert_point('LI3','large_intestine',3,'San Jian','三间','Third Space','front',192.5,311.5,true,'upper','hand');
perform public.catalogue_upsert_point('LI4','large_intestine',4,'He Gu','合谷','Joining Valley','front',189.8,296.2,true,'upper','hand');
perform public.catalogue_upsert_point('LI5','large_intestine',5,'Yang Xi','阳溪','Yang Ravine','front',186.8,280.9,true,'upper','wrist');
perform public.catalogue_upsert_point('LI6','large_intestine',6,'Pian Li','偏历','Veering Passage','front',184.8,265.5,true,'upper','forearm');
perform public.catalogue_upsert_point('LI7','large_intestine',7,'Wen Liu','温溜','Warm Dwelling','front',183.1,250.1,true,'upper','forearm');
perform public.catalogue_upsert_point('LI8','large_intestine',8,'Xia Lian','下廉','Lower Ridge','front',181.4,234.7,true,'upper','forearm');
perform public.catalogue_upsert_point('LI9','large_intestine',9,'Shang Lian','上廉','Upper Ridge','front',179.5,219.2,true,'upper','forearm');
perform public.catalogue_upsert_point('LI10','large_intestine',10,'Shou San Li','手三里','Arm Three Li','front',177.7,203.8,true,'upper','forearm');
perform public.catalogue_upsert_point('LI11','large_intestine',11,'Qu Chi','曲池','Pool at the Bend','front',175.9,188.4,true,'upper','elbow');
perform public.catalogue_upsert_point('LI12','large_intestine',12,'Zhou Liao','肘髎','Elbow Bone-Hole','front',175.0,172.9,true,'upper','upper_arm');
perform public.catalogue_upsert_point('LI13','large_intestine',13,'Shou Wu Li','手五里','Arm Five Li','front',174.1,157.3,true,'upper','upper_arm');
perform public.catalogue_upsert_point('LI14','large_intestine',14,'Bi Nao','臂臑','Upper Arm','front',173.2,141.8,true,'upper','upper_arm');
perform public.catalogue_upsert_point('LI15','large_intestine',15,'Jian Yu','肩髃','Shoulder Bone','front',172.3,126.3,true,'upper','shoulder');
perform public.catalogue_upsert_point('LI16','large_intestine',16,'Ju Gu','巨骨','Great Bone','front',164.4,113.7,true,'upper','shoulder');
perform public.catalogue_upsert_point('LI17','large_intestine',17,'Tian Ding','天鼎','Celestial Vessel','front',153.9,102.3,true,'upper','neck');
perform public.catalogue_upsert_point('LI18','large_intestine',18,'Fu Tu','扶突','Protuberance Assistant','front',143.0,91.2,true,'upper','neck');
perform public.catalogue_upsert_point('LI19','large_intestine',19,'Kou He Liao','口禾髎','Mouth Grain Bone-Hole','front',131.8,80.5,true,'upper','face');
perform public.catalogue_upsert_point('LI20','large_intestine',20,'Ying Xiang','迎香','Welcome Fragrance','front',120.0,70.4,true,'upper','face');
-- ST · stomach
perform public.catalogue_upsert_point('ST1','stomach',1,'Cheng Qi','承泣','Tear Container','front',123.0,59.0,true,'upper','face');
perform public.catalogue_upsert_point('ST2','stomach',2,'Si Bai','四白','Four Whites','front',125.6,69.8,true,'upper','face');
perform public.catalogue_upsert_point('ST3','stomach',3,'Ju Liao','巨髎','Great Bone-Hole','front',128.1,80.7,true,'upper','face');
perform public.catalogue_upsert_point('ST4','stomach',4,'Di Cang','地仓','Earth Granary','front',129.6,91.6,true,'upper','face');
perform public.catalogue_upsert_point('ST5','stomach',5,'Da Ying','大迎','Great Reception','front',126.6,102.4,true,'upper','face');
perform public.catalogue_upsert_point('ST6','stomach',6,'Jia Che','颊车','Jaw Bone','front',129.3,112.9,true,'upper','face');
perform public.catalogue_upsert_point('ST7','stomach',7,'Xia Guan','下关','Below the Joint','front',132.7,123.4,true,'upper','face');
perform public.catalogue_upsert_point('ST8','stomach',8,'Tou Wei','头维','Head Corner','front',134.9,134.4,true,'upper','face');
perform public.catalogue_upsert_point('ST9','stomach',9,'Ren Ying','人迎','Man Welcome','front',137.1,145.3,true,'upper','neck');
perform public.catalogue_upsert_point('ST10','stomach',10,'Shui Tu','水突','Water Prominence','front',139.3,156.3,true,'upper','neck');
perform public.catalogue_upsert_point('ST11','stomach',11,'Qi She','气舍','Qi Abode','front',138.2,167.1,true,'upper','neck');
perform public.catalogue_upsert_point('ST12','stomach',12,'Que Pen','缺盆','Empty Basin','front',135.4,177.9,true,'upper','shoulder');
perform public.catalogue_upsert_point('ST13','stomach',13,'Qi Hu','气户','Qi Door','front',132.6,188.7,true,'upper','chest');
perform public.catalogue_upsert_point('ST14','stomach',14,'Ku Fang','库房','Storeroom','front',131.0,199.7,true,'upper','chest');
perform public.catalogue_upsert_point('ST15','stomach',15,'Wu Yi','屋翳','Roof','front',131.0,210.8,true,'upper','chest');
perform public.catalogue_upsert_point('ST16','stomach',16,'Ying Chuang','膺窗','Breast Window','front',131.0,222.0,true,'upper','chest');
perform public.catalogue_upsert_point('ST17','stomach',17,'Ru Zhong','乳中','Breast Centre','front',131.0,233.2,true,'upper','chest');
perform public.catalogue_upsert_point('ST18','stomach',18,'Ru Gen','乳根','Breast Root','front',131.0,244.3,true,'upper','chest');
perform public.catalogue_upsert_point('ST19','stomach',19,'Bu Rong','不容','Not Contained','front',131.0,255.5,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST20','stomach',20,'Cheng Man','承满','Assuming Fullness','front',131.0,266.6,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST21','stomach',21,'Liang Men','梁门','Beam Gate','front',131.0,277.8,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST22','stomach',22,'Guan Men','关门','Pass Gate','front',131.9,288.9,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST23','stomach',23,'Tai Yi','太乙','Supreme Unity','front',133.6,299.9,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST24','stomach',24,'Hua Rou Men','滑肉门','Slippery Flesh Gate','front',134.8,311.0,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST25','stomach',25,'Tian Shu','天枢','Celestial Pivot','front',136.0,322.1,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST26','stomach',26,'Wai Ling','外陵','Outer Mound','front',137.1,333.2,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST27','stomach',27,'Da Ju','大巨','Great Gigantic','front',138.1,344.3,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST28','stomach',28,'Shui Dao','水道','Water Passage','front',138.4,355.5,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST29','stomach',29,'Gui Lai','归来','Return','front',138.8,366.6,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST30','stomach',30,'Qi Chong','气冲','Rushing Qi','front',139.1,377.8,true,'upper','abdomen');
perform public.catalogue_upsert_point('ST31','stomach',31,'Bi Guan','髀关','Thigh Joint','front',139.5,388.9,true,'lower','thigh');
perform public.catalogue_upsert_point('ST32','stomach',32,'Fu Tu','伏兔','Crouching Rabbit','front',139.8,400.1,true,'lower','thigh');
perform public.catalogue_upsert_point('ST33','stomach',33,'Yin Shi','阴市','Yin Market','front',140.0,411.2,true,'lower','thigh');
perform public.catalogue_upsert_point('ST34','stomach',34,'Liang Qiu','梁丘','Ridge Mound','front',140.0,422.4,true,'lower','thigh');
perform public.catalogue_upsert_point('ST35','stomach',35,'Du Bi','犊鼻','Calf''s Nose','front',140.0,433.6,true,'lower','knee');
perform public.catalogue_upsert_point('ST36','stomach',36,'Zu San Li','足三里','Leg Three Li','front',140.0,444.7,true,'lower','lower_leg');
perform public.catalogue_upsert_point('ST37','stomach',37,'Shang Ju Xu','上巨虚','Upper Great Hollow','front',139.4,455.9,true,'lower','lower_leg');
perform public.catalogue_upsert_point('ST38','stomach',38,'Tiao Kou','条口','Ribbon Opening','front',139.0,467.0,true,'lower','lower_leg');
perform public.catalogue_upsert_point('ST39','stomach',39,'Xia Ju Xu','下巨虚','Lower Great Hollow','front',138.8,478.2,true,'lower','lower_leg');
perform public.catalogue_upsert_point('ST40','stomach',40,'Feng Long','丰隆','Bountiful Bulge','front',138.6,489.3,true,'lower','lower_leg');
perform public.catalogue_upsert_point('ST41','stomach',41,'Jie Xi','解溪','Ravine Divide','front',138.4,500.5,true,'lower','ankle');
perform public.catalogue_upsert_point('ST42','stomach',42,'Chong Yang','冲阳','Surging Yang','front',138.2,511.6,true,'lower','foot');
perform public.catalogue_upsert_point('ST43','stomach',43,'Xian Gu','陷谷','Sunken Valley','front',138.0,522.8,true,'lower','foot');
perform public.catalogue_upsert_point('ST44','stomach',44,'Nei Ting','内庭','Inner Court','front',137.3,533.9,true,'lower','foot');
perform public.catalogue_upsert_point('ST45','stomach',45,'Li Dui','厉兑','Severe Mouth','front',136.0,545.0,true,'lower','foot');
-- SP · spleen
perform public.catalogue_upsert_point('SP1','spleen',1,'Yin Bai','隐白','Hidden White','front',128.0,545.0,true,'lower','foot');
perform public.catalogue_upsert_point('SP2','spleen',2,'Da Du','大都','Great Metropolis','front',123.2,524.6,true,'lower','foot');
perform public.catalogue_upsert_point('SP3','spleen',3,'Tai Bai','太白','Supreme White','front',122.7,503.6,true,'lower','foot');
perform public.catalogue_upsert_point('SP4','spleen',4,'Gong Sun','公孙','Yellow Emperor','front',122.3,482.5,true,'lower','foot');
perform public.catalogue_upsert_point('SP5','spleen',5,'Shang Qiu','商丘','Shang Hill','front',122.2,461.5,true,'lower','ankle');
perform public.catalogue_upsert_point('SP6','spleen',6,'San Yin Jiao','三阴交','Three Yin Intersection','front',123.6,440.5,true,'lower','lower_leg');
perform public.catalogue_upsert_point('SP7','spleen',7,'Lou Gu','漏谷','Leaking Valley','front',125.5,419.5,true,'lower','lower_leg');
perform public.catalogue_upsert_point('SP8','spleen',8,'Di Ji','地机','Earth Pivot','front',127.3,398.5,true,'lower','lower_leg');
perform public.catalogue_upsert_point('SP9','spleen',9,'Yin Ling Quan','阴陵泉','Yin Mound Spring','front',128.3,377.5,true,'lower','knee');
perform public.catalogue_upsert_point('SP10','spleen',10,'Xue Hai','血海','Sea of Blood','front',129.3,356.5,true,'lower','thigh');
perform public.catalogue_upsert_point('SP11','spleen',11,'Ji Men','箕门','Winnower Gate','front',130.8,335.5,true,'lower','thigh');
perform public.catalogue_upsert_point('SP12','spleen',12,'Chong Men','冲门','Surging Gate','front',133.4,314.6,true,'upper','abdomen');
perform public.catalogue_upsert_point('SP13','spleen',13,'Fu She','府舍','Bowel Abode','front',135.9,293.7,true,'upper','abdomen');
perform public.catalogue_upsert_point('SP14','spleen',14,'Fu Jie','腹结','Abdominal Bind','front',140.1,273.2,true,'upper','abdomen');
perform public.catalogue_upsert_point('SP15','spleen',15,'Da Heng','大横','Great Horizontal','front',142.5,252.3,true,'upper','abdomen');
perform public.catalogue_upsert_point('SP16','spleen',16,'Fu Ai','腹哀','Abdominal Lament','front',144.8,231.3,true,'upper','abdomen');
perform public.catalogue_upsert_point('SP17','spleen',17,'Shi Dou','食窦','Food Hole','front',146.1,210.3,true,'upper','chest');
perform public.catalogue_upsert_point('SP18','spleen',18,'Tian Xi','天溪','Celestial Ravine','front',147.6,189.3,true,'upper','chest');
perform public.catalogue_upsert_point('SP19','spleen',19,'Xiong Xiang','胸乡','Chest Village','front',150.0,168.4,true,'upper','chest');
perform public.catalogue_upsert_point('SP20','spleen',20,'Zhou Rong','周荣','Encircling Glory','front',152.9,147.6,true,'upper','chest');
perform public.catalogue_upsert_point('SP21','spleen',21,'Da Bao','大包','Great Embracement','front',158.0,127.4,true,'upper','chest');
-- HT · heart
perform public.catalogue_upsert_point('HT1','heart',1,'Ji Quan','极泉','Highest Spring','front',154.0,133.4,true,'upper','shoulder');
perform public.catalogue_upsert_point('HT2','heart',2,'Qing Ling','青灵','Green Spirit','front',162.3,158.7,true,'upper','upper_arm');
perform public.catalogue_upsert_point('HT3','heart',3,'Shao Hai','少海','Lesser Sea','front',167.2,184.8,true,'upper','elbow');
perform public.catalogue_upsert_point('HT4','heart',4,'Ling Dao','灵道','Spirit Pathway','front',171.1,211.2,true,'upper','forearm');
perform public.catalogue_upsert_point('HT5','heart',5,'Tong Li','通里','Connecting Li','front',175.3,237.5,true,'upper','forearm');
perform public.catalogue_upsert_point('HT6','heart',6,'Yin Xi','阴郄','Yin Cleft','front',179.7,263.8,true,'upper','forearm');
perform public.catalogue_upsert_point('HT7','heart',7,'Shen Men','神门','Spirit Gate','front',184.6,290.0,true,'upper','wrist');
perform public.catalogue_upsert_point('HT8','heart',8,'Shao Fu','少府','Lesser Mansion','front',190.1,316.0,true,'upper','hand');
perform public.catalogue_upsert_point('HT9','heart',9,'Shao Chong','少冲','Lesser Surge','front',196.0,342.0,true,'upper','hand');
-- SI · small_intestine
perform public.catalogue_upsert_point('SI1','small_intestine',1,'Shao Ze','少泽','Lesser Marsh','back',196.0,342.0,true,'upper','hand');
perform public.catalogue_upsert_point('SI2','small_intestine',2,'Qian Gu','前谷','Front Valley','back',192.3,325.9,true,'upper','hand');
perform public.catalogue_upsert_point('SI3','small_intestine',3,'Hou Xi','后溪','Back Ravine','back',188.6,309.7,true,'upper','hand');
perform public.catalogue_upsert_point('SI4','small_intestine',4,'Wan Gu','腕骨','Wrist Bone','back',185.3,293.5,true,'upper','hand');
perform public.catalogue_upsert_point('SI5','small_intestine',5,'Yang Gu','阳谷','Yang Valley','back',182.1,277.3,true,'upper','wrist');
perform public.catalogue_upsert_point('SI6','small_intestine',6,'Yang Lao','养老','Nursing the Aged','back',182.7,260.8,true,'upper','forearm');
perform public.catalogue_upsert_point('SI7','small_intestine',7,'Zhi Zheng','支正','Branch to the Correct','back',183.4,244.3,true,'upper','forearm');
perform public.catalogue_upsert_point('SI8','small_intestine',8,'Xiao Hai','小海','Small Sea','back',183.5,227.8,true,'upper','elbow');
perform public.catalogue_upsert_point('SI9','small_intestine',9,'Jian Zhen','肩贞','True Shoulder','back',179.7,211.7,true,'upper','shoulder');
perform public.catalogue_upsert_point('SI10','small_intestine',10,'Nao Shu','臑俞','Upper Arm Shu','back',175.9,195.6,true,'upper','shoulder');
perform public.catalogue_upsert_point('SI11','small_intestine',11,'Tian Zong','天宗','Celestial Gathering','back',172.1,179.5,true,'upper','upper_back');
perform public.catalogue_upsert_point('SI12','small_intestine',12,'Bing Feng','秉风','Grasping the Wind','back',168.3,163.4,true,'upper','upper_back');
perform public.catalogue_upsert_point('SI13','small_intestine',13,'Qu Yuan','曲垣','Crooked Wall','back',163.9,147.4,true,'upper','upper_back');
perform public.catalogue_upsert_point('SI14','small_intestine',14,'Jian Wai Shu','肩外俞','Outer Shoulder Shu','back',160.5,131.5,true,'upper','upper_back');
perform public.catalogue_upsert_point('SI15','small_intestine',15,'Jian Zhong Shu','肩中俞','Middle Shoulder Shu','back',162.0,116.3,true,'upper','neck');
perform public.catalogue_upsert_point('SI16','small_intestine',16,'Tian Chuang','天窗','Celestial Window','back',149.6,105.4,true,'upper','neck');
perform public.catalogue_upsert_point('SI17','small_intestine',17,'Tian Rong','天容','Celestial Countenance','back',140.0,92.3,true,'upper','neck');
perform public.catalogue_upsert_point('SI18','small_intestine',18,'Quan Liao','颧髎','Cheek Bone-Hole','back',133.4,77.2,true,'upper','face');
perform public.catalogue_upsert_point('SI19','small_intestine',19,'Ting Gong','听宫','Auditory Palace','back',130.0,61.0,true,'upper','face');
-- BL · bladder
perform public.catalogue_upsert_point('BL1','bladder',1,'Jing Ming','睛明','Bright Eyes','front',120.0,57.0,true,'upper','face');
perform public.catalogue_upsert_point('BL2','bladder',2,'Zan Zhu','攒竹','Gathered Bamboo','front',124.0,47.0,true,'upper','face');
perform public.catalogue_upsert_point('BL3','bladder',3,'Mei Chong','眉冲','Eyebrow Ascension','back',122.0,38.1,true,'upper','head');
perform public.catalogue_upsert_point('BL4','bladder',4,'Qu Cha','曲差','Deviating Turn','back',126.0,32.1,true,'upper','head');
perform public.catalogue_upsert_point('BL5','bladder',5,'Wu Chu','五处','Fifth Place','back',126.0,26.1,true,'upper','head');
perform public.catalogue_upsert_point('BL6','bladder',6,'Cheng Guang','承光','Receiving Light','back',125.0,30.1,true,'upper','head');
perform public.catalogue_upsert_point('BL7','bladder',7,'Tong Tian','通天','Celestial Connection','back',124.0,40.1,true,'upper','head');
perform public.catalogue_upsert_point('BL8','bladder',8,'Luo Que','络却','Declining Connection','back',123.0,56.1,true,'upper','head');
perform public.catalogue_upsert_point('BL9','bladder',9,'Yu Zhen','玉枕','Jade Pillow','back',123.0,65.0,true,'upper','head');
perform public.catalogue_upsert_point('BL10','bladder',10,'Tian Zhu','天柱','Celestial Pillar','back',124.0,96.5,true,'upper','neck');
perform public.catalogue_upsert_point('BL11','bladder',11,'Da Zhu','大杼','Great Shuttle','back',125.0,118.0,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL12','bladder',12,'Feng Men','风门','Wind Gate','back',125.0,126.7,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL13','bladder',13,'Fei Shu','肺俞','Lung Shu','back',125.0,135.3,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL14','bladder',14,'Jue Yin Shu','厥阴俞','Jue Yin Shu','back',125.0,144.0,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL15','bladder',15,'Xin Shu','心俞','Heart Shu','back',125.0,152.6,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL16','bladder',16,'Du Shu','督俞','Governing Shu','back',125.0,161.3,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL17','bladder',17,'Ge Shu','膈俞','Diaphragm Shu','back',125.0,169.9,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL18','bladder',18,'Gan Shu','肝俞','Liver Shu','back',125.0,178.6,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL19','bladder',19,'Dan Shu','胆俞','Gallbladder Shu','back',125.0,187.3,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL20','bladder',20,'Pi Shu','脾俞','Spleen Shu','back',125.0,195.9,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL21','bladder',21,'Wei Shu','胃俞','Stomach Shu','back',125.0,204.6,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL22','bladder',22,'San Jiao Shu','三焦俞','Triple Burner Shu','back',125.0,213.2,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL23','bladder',23,'Shen Shu','肾俞','Kidney Shu','back',125.0,221.9,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL24','bladder',24,'Qi Hai Shu','气海俞','Sea of Qi Shu','back',125.0,230.6,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL25','bladder',25,'Da Chang Shu','大肠俞','Large Intestine Shu','back',125.0,239.2,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL26','bladder',26,'Guan Yuan Shu','关元俞','Origin Pass Shu','back',125.0,247.9,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL27','bladder',27,'Xiao Chang Shu','小肠俞','Small Intestine Shu','back',125.0,256.5,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL28','bladder',28,'Pang Guang Shu','膀胱俞','Bladder Shu','back',125.0,265.2,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL29','bladder',29,'Zhong Lu Shu','中膂俞','Central Backbone Shu','back',125.0,273.8,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL30','bladder',30,'Bai Huan Shu','白环俞','White Ring Shu','back',125.0,282.5,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL31','bladder',31,'Shang Liao','上髎','Upper Bone-Hole','back',119.0,276.5,true,'upper','sacrum');
perform public.catalogue_upsert_point('BL32','bladder',32,'Ci Liao','次髎','Second Bone-Hole','back',119.0,286.5,true,'upper','sacrum');
perform public.catalogue_upsert_point('BL33','bladder',33,'Zhong Liao','中髎','Central Bone-Hole','back',119.0,296.5,true,'upper','sacrum');
perform public.catalogue_upsert_point('BL34','bladder',34,'Xia Liao','下髎','Lower Bone-Hole','back',119.0,306.5,true,'upper','sacrum');
perform public.catalogue_upsert_point('BL35','bladder',35,'Hui Yang','会阳','Meeting of Yang','back',123.0,303.0,true,'upper','buttock');
perform public.catalogue_upsert_point('BL36','bladder',36,'Cheng Fu','承扶','Support','back',134.0,315.0,true,'lower','thigh');
perform public.catalogue_upsert_point('BL37','bladder',37,'Yin Men','殷门','Gate of Abundance','back',136.0,342.0,true,'lower','thigh');
perform public.catalogue_upsert_point('BL38','bladder',38,'Fu Xi','浮郄','Superficial Cleft','back',139.0,385.0,true,'lower','knee');
perform public.catalogue_upsert_point('BL39','bladder',39,'Wei Yang','委阳','Bend Yang','back',142.0,401.0,true,'lower','knee');
perform public.catalogue_upsert_point('BL40','bladder',40,'Wei Zhong','委中','Bend Middle','back',137.0,405.0,true,'lower','knee');
perform public.catalogue_upsert_point('BL41','bladder',41,'Fu Fen','附分','Attached Branch','back',140.0,122.0,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL42','bladder',42,'Po Hu','魄户','Corporeal Soul Door','back',140.0,135.2,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL43','bladder',43,'Gao Huang','膏肓','Vital Region Shu','back',140.0,148.3,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL44','bladder',44,'Shen Tang','神堂','Spirit Hall','back',140.0,161.5,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL45','bladder',45,'Yi Xi','譩譆','Yi Xi','back',140.0,174.6,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL46','bladder',46,'Ge Guan','膈关','Diaphragm Pass','back',140.0,187.8,true,'upper','upper_back');
perform public.catalogue_upsert_point('BL47','bladder',47,'Hun Men','魂门','Ethereal Soul Gate','back',140.0,200.9,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL48','bladder',48,'Yang Gang','阳纲','Yang Headrope','back',140.0,214.1,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL49','bladder',49,'Yi She','意舍','Reflection Abode','back',140.0,227.2,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL50','bladder',50,'Wei Cang','胃仓','Stomach Granary','back',140.0,240.4,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL51','bladder',51,'Huang Men','肓门','Vitals Gate','back',140.0,253.5,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL52','bladder',52,'Zhi Shi','志室','Will Chamber','back',140.0,266.7,true,'upper','lower_back');
perform public.catalogue_upsert_point('BL53','bladder',53,'Bao Huang','胞肓','Bladder Vitals','back',140.0,279.8,true,'upper','buttock');
perform public.catalogue_upsert_point('BL54','bladder',54,'Zhi Bian','秩边','Order Limit','back',140.0,293.0,true,'upper','buttock');
perform public.catalogue_upsert_point('BL55','bladder',55,'He Yang','合阳','Yang Union','back',137.0,435.0,true,'lower','lower_leg');
perform public.catalogue_upsert_point('BL56','bladder',56,'Cheng Jin','承筋','Sinew Support','back',137.0,450.5,true,'lower','lower_leg');
perform public.catalogue_upsert_point('BL57','bladder',57,'Cheng Shan','承山','Mountain Support','back',137.0,470.5,true,'lower','lower_leg');
perform public.catalogue_upsert_point('BL58','bladder',58,'Fei Yang','飞扬','Taking Flight','back',140.0,490.5,true,'lower','lower_leg');
perform public.catalogue_upsert_point('BL59','bladder',59,'Fu Yang','跗阳','Instep Yang','back',140.0,508.0,true,'lower','ankle');
perform public.catalogue_upsert_point('BL60','bladder',60,'Kun Lun','昆仑','Kunlun Mountains','back',141.0,524.0,true,'lower','ankle');
perform public.catalogue_upsert_point('BL61','bladder',61,'Pu Can','仆参','Servant''s Respect','back',141.0,539.4,true,'lower','ankle');
perform public.catalogue_upsert_point('BL62','bladder',62,'Shen Mai','申脉','Extending Vessel','back',142.0,530.0,true,'lower','foot');
perform public.catalogue_upsert_point('BL63','bladder',63,'Jin Men','金门','Metal Gate','back',142.0,543.4,true,'lower','foot');
perform public.catalogue_upsert_point('BL64','bladder',64,'Jing Gu','京骨','Capital Bone','back',142.0,535.0,true,'lower','foot');
perform public.catalogue_upsert_point('BL65','bladder',65,'Shu Gu','束骨','Bundle Bone','back',141.0,540.0,true,'lower','foot');
perform public.catalogue_upsert_point('BL66','bladder',66,'Zu Tong Gu','足通谷','Valley Passage','back',141.0,544.0,true,'lower','foot');
perform public.catalogue_upsert_point('BL67','bladder',67,'Zhi Yin','至阴','Reaching Yin','back',140.0,548.0,true,'lower','foot');
-- KI · kidney
perform public.catalogue_upsert_point('KI1','kidney',1,'Yong Quan','涌泉','Gushing Spring','front',128.0,547.0,true,'lower','foot');
perform public.catalogue_upsert_point('KI2','kidney',2,'Ran Gu','然谷','Blazing Valley','front',123.4,530.9,true,'lower','foot');
perform public.catalogue_upsert_point('KI3','kidney',3,'Tai Xi','太溪','Great Ravine','front',121.8,514.3,true,'lower','ankle');
perform public.catalogue_upsert_point('KI4','kidney',4,'Da Zhong','大钟','Large Goblet','front',121.6,497.5,true,'lower','ankle');
perform public.catalogue_upsert_point('KI5','kidney',5,'Shui Quan','水泉','Water Spring','front',121.3,480.7,true,'lower','ankle');
perform public.catalogue_upsert_point('KI6','kidney',6,'Zhao Hai','照海','Shining Sea','front',121.0,463.9,true,'lower','ankle');
perform public.catalogue_upsert_point('KI7','kidney',7,'Fu Liu','复溜','Recover Flow','front',121.6,447.1,true,'lower','lower_leg');
perform public.catalogue_upsert_point('KI8','kidney',8,'Jiao Xin','交信','Intersection Reach','front',122.3,430.3,true,'lower','lower_leg');
perform public.catalogue_upsert_point('KI9','kidney',9,'Zhu Bin','筑宾','Guest House','front',123.4,413.5,true,'lower','lower_leg');
perform public.catalogue_upsert_point('KI10','kidney',10,'Yin Gu','阴谷','Yin Valley','front',123.7,396.8,true,'lower','knee');
perform public.catalogue_upsert_point('KI11','kidney',11,'Heng Gu','横骨','Pubic Bone','front',123.0,380.0,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI12','kidney',12,'Da He','大赫','Great Manifestation','front',122.3,363.2,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI13','kidney',13,'Qi Xue','气穴','Qi Hole','front',121.6,346.4,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI14','kidney',14,'Si Man','四满','Fourfold Fullness','front',120.9,329.6,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI15','kidney',15,'Zhong Zhu','中注','Central Flow','front',120.2,312.8,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI16','kidney',16,'Huang Shu','肓俞','Vitals Shu','front',119.6,296.1,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI17','kidney',17,'Shang Qu','商曲','Shang Bend','front',119.0,279.3,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI18','kidney',18,'Shi Guan','石关','Stone Pass','front',119.0,262.5,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI19','kidney',19,'Yin Du','阴都','Yin Metropolis','front',119.0,245.7,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI20','kidney',20,'Fu Tong Gu','腹通谷','Abdominal Passage Valley','front',119.1,228.9,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI21','kidney',21,'You Men','幽门','Dark Gate','front',120.0,212.1,true,'upper','abdomen');
perform public.catalogue_upsert_point('KI22','kidney',22,'Bu Lang','步廊','Corridor Walk','front',121.0,195.3,true,'upper','chest');
perform public.catalogue_upsert_point('KI23','kidney',23,'Shen Feng','神封','Spirit Seal','front',123.3,178.7,true,'upper','chest');
perform public.catalogue_upsert_point('KI24','kidney',24,'Ling Xu','灵墟','Spirit Mound','front',125.7,162.1,true,'upper','chest');
perform public.catalogue_upsert_point('KI25','kidney',25,'Shen Cang','神藏','Spirit Storehouse','front',127.5,145.4,true,'upper','chest');
perform public.catalogue_upsert_point('KI26','kidney',26,'Yu Zhong','彧中','Lively Centre','front',129.3,128.7,true,'upper','chest');
perform public.catalogue_upsert_point('KI27','kidney',27,'Shu Fu','俞府','Shu Mansion','front',130.0,111.9,true,'upper','chest');
-- PC · pericardium
perform public.catalogue_upsert_point('PC1','pericardium',1,'Tian Chi','天池','Celestial Pool','front',156.0,137.4,true,'upper','chest');
perform public.catalogue_upsert_point('PC2','pericardium',2,'Tian Quan','天泉','Celestial Spring','front',164.6,162.0,true,'upper','upper_arm');
perform public.catalogue_upsert_point('PC3','pericardium',3,'Qu Ze','曲泽','Marsh at the Bend','front',169.4,187.7,true,'upper','elbow');
perform public.catalogue_upsert_point('PC4','pericardium',4,'Xi Men','郄门','Cleft Gate','front',173.4,213.5,true,'upper','forearm');
perform public.catalogue_upsert_point('PC5','pericardium',5,'Jian Shi','间使','Intermediary Courier','front',177.5,239.3,true,'upper','forearm');
perform public.catalogue_upsert_point('PC6','pericardium',6,'Nei Guan','内关','Inner Pass','front',181.5,265.0,true,'upper','forearm');
perform public.catalogue_upsert_point('PC7','pericardium',7,'Da Ling','大陵','Great Mound','front',185.9,290.8,true,'upper','wrist');
perform public.catalogue_upsert_point('PC8','pericardium',8,'Lao Gong','劳宫','Palace of Toil','front',191.1,316.4,true,'upper','hand');
perform public.catalogue_upsert_point('PC9','pericardium',9,'Zhong Chong','中冲','Central Hub','front',196.0,342.0,true,'upper','hand');
-- SJ · san_jiao
perform public.catalogue_upsert_point('SJ1','san_jiao',1,'Guan Chong','关冲','Passage Hub','back',198.0,342.0,true,'upper','hand');
perform public.catalogue_upsert_point('SJ2','san_jiao',2,'Ye Men','液门','Humour Gate','back',195.7,328.4,true,'upper','hand');
perform public.catalogue_upsert_point('SJ3','san_jiao',3,'Zhong Zhu','中渚','Central Islet','back',192.3,315.1,true,'upper','hand');
perform public.catalogue_upsert_point('SJ4','san_jiao',4,'Yang Chi','阳池','Yang Pool','back',189.1,301.7,true,'upper','wrist');
perform public.catalogue_upsert_point('SJ5','san_jiao',5,'Wai Guan','外关','Outer Pass','back',186.7,288.2,true,'upper','forearm');
perform public.catalogue_upsert_point('SJ6','san_jiao',6,'Zhi Gou','支沟','Branch Ditch','back',184.3,274.6,true,'upper','forearm');
perform public.catalogue_upsert_point('SJ7','san_jiao',7,'Hui Zong','会宗','Convergence and Gathering','back',182.9,260.9,true,'upper','forearm');
perform public.catalogue_upsert_point('SJ8','san_jiao',8,'San Yang Luo','三阳络','Three Yang Connection','back',181.6,247.2,true,'upper','forearm');
perform public.catalogue_upsert_point('SJ9','san_jiao',9,'Si Du','四渎','Four Rivers','back',180.3,233.5,true,'upper','forearm');
perform public.catalogue_upsert_point('SJ10','san_jiao',10,'Tian Jing','天井','Celestial Well','back',178.8,219.8,true,'upper','elbow');
perform public.catalogue_upsert_point('SJ11','san_jiao',11,'Qing Leng Yuan','清冷渊','Clear Cold Abyss','back',177.1,206.2,true,'upper','upper_arm');
perform public.catalogue_upsert_point('SJ12','san_jiao',12,'Xiao Luo','消泺','Dispersing Riverbed','back',175.5,192.5,true,'upper','upper_arm');
perform public.catalogue_upsert_point('SJ13','san_jiao',13,'Nao Hui','臑会','Upper Arm Convergence','back',173.8,178.8,true,'upper','upper_arm');
perform public.catalogue_upsert_point('SJ14','san_jiao',14,'Jian Liao','肩髎','Shoulder Bone-Hole','back',172.1,165.2,true,'upper','shoulder');
perform public.catalogue_upsert_point('SJ15','san_jiao',15,'Tian Liao','天髎','Celestial Bone-Hole','back',172.0,151.4,true,'upper','shoulder');
perform public.catalogue_upsert_point('SJ16','san_jiao',16,'Tian You','天牖','Celestial Window','back',172.0,137.6,true,'upper','neck');
perform public.catalogue_upsert_point('SJ17','san_jiao',17,'Yi Feng','翳风','Wind Screen','back',172.0,123.9,true,'upper','ear');
perform public.catalogue_upsert_point('SJ18','san_jiao',18,'Chi Mai','瘛脉','Spasm Vessel','back',164.9,113.1,true,'upper','ear');
perform public.catalogue_upsert_point('SJ19','san_jiao',19,'Lu Xi','颅息','Skull Rest','back',155.1,103.5,true,'upper','ear');
perform public.catalogue_upsert_point('SJ20','san_jiao',20,'Jiao Sun','角孙','Angle Vertex','back',146.1,93.2,true,'upper','ear');
perform public.catalogue_upsert_point('SJ21','san_jiao',21,'Er Men','耳门','Ear Gate','back',139.1,81.3,true,'upper','ear');
perform public.catalogue_upsert_point('SJ22','san_jiao',22,'Er He Liao','耳和髎','Harmony Bone-Hole','back',134.6,68.5,true,'upper','ear');
perform public.catalogue_upsert_point('SJ23','san_jiao',23,'Si Zhu Kong','丝竹空','Silk Bamboo Hole','back',132.0,55.0,true,'upper','face');
-- GB · gallbladder
perform public.catalogue_upsert_point('GB1','gallbladder',1,'Tong Zi Liao','瞳子髎','Pupil Bone-Hole','front',132.0,55.0,true,'upper','face');
perform public.catalogue_upsert_point('GB2','gallbladder',2,'Ting Hui','听会','Auditory Convergence','front',134.0,67.0,true,'upper','face');
perform public.catalogue_upsert_point('GB3','gallbladder',3,'Shang Guan','上关','Upper Gate','front',134.0,57.0,true,'upper','head');
perform public.catalogue_upsert_point('GB4','gallbladder',4,'Han Yan','颔厌','Jaw Serenity','front',133.0,44.1,true,'upper','head');
perform public.catalogue_upsert_point('GB5','gallbladder',5,'Xuan Lu','悬颅','Suspended Skull','front',134.0,52.1,true,'upper','head');
perform public.catalogue_upsert_point('GB6','gallbladder',6,'Xuan Li','悬厘','Suspended Tuft','front',134.0,60.1,true,'upper','head');
perform public.catalogue_upsert_point('GB7','gallbladder',7,'Qu Bin','曲鬓','Temporal Hairline Curve','front',135.0,68.1,true,'upper','head');
perform public.catalogue_upsert_point('GB8','gallbladder',8,'Shuai Gu','率谷','Valley Lead','front',133.0,36.1,true,'upper','head');
perform public.catalogue_upsert_point('GB9','gallbladder',9,'Tian Chong','天冲','Celestial Hub','back',132.0,36.1,true,'upper','head');
perform public.catalogue_upsert_point('GB10','gallbladder',10,'Fu Bai','浮白','Floating White','back',133.0,48.1,true,'upper','head');
perform public.catalogue_upsert_point('GB11','gallbladder',11,'Tou Qiao Yin','头窍阴','Head Portal Yin','back',133.0,60.1,true,'upper','head');
perform public.catalogue_upsert_point('GB12','gallbladder',12,'Wan Gu','完骨','Completion Bone','back',131.0,76.0,true,'upper','head');
perform public.catalogue_upsert_point('GB13','gallbladder',13,'Ben Shen','本神','Root Spirit','front',127.0,34.1,true,'upper','head');
perform public.catalogue_upsert_point('GB14','gallbladder',14,'Yang Bai','阳白','Yang White','front',123.0,43.0,true,'upper','head');
perform public.catalogue_upsert_point('GB15','gallbladder',15,'Tou Lin Qi','头临泣','Head Overlooking Tears','back',123.0,28.1,true,'upper','head');
perform public.catalogue_upsert_point('GB16','gallbladder',16,'Mu Chuang','目窗','Eye Window','back',124.0,26.1,true,'upper','head');
perform public.catalogue_upsert_point('GB17','gallbladder',17,'Zheng Ying','正营','Upright Construction','back',124.0,30.1,true,'upper','head');
perform public.catalogue_upsert_point('GB18','gallbladder',18,'Cheng Ling','承灵','Spirit Support','back',124.0,40.1,true,'upper','head');
perform public.catalogue_upsert_point('GB19','gallbladder',19,'Nao Kong','脑空','Brain Hollow','back',125.0,59.0,true,'upper','head');
perform public.catalogue_upsert_point('GB20','gallbladder',20,'Feng Chi','风池','Wind Pool','back',128.0,90.5,true,'upper','head');
perform public.catalogue_upsert_point('GB21','gallbladder',21,'Jian Jing','肩井','Shoulder Well','back',150.0,108.0,true,'upper','shoulder');
perform public.catalogue_upsert_point('GB22','gallbladder',22,'Yuan Ye','渊腋','Armpit Abyss','front',157.0,154.0,true,'upper','chest');
perform public.catalogue_upsert_point('GB23','gallbladder',23,'Zhe Jin','辄筋','Flank Sinews','front',157.0,166.0,true,'upper','chest');
perform public.catalogue_upsert_point('GB24','gallbladder',24,'Ri Yue','日月','Sun and Moon','front',154.0,201.0,true,'upper','chest');
perform public.catalogue_upsert_point('GB25','gallbladder',25,'Jing Men','京门','Capital Gate','front',151.0,224.4,true,'upper','abdomen');
perform public.catalogue_upsert_point('GB26','gallbladder',26,'Dai Mai','带脉','Girdling Vessel','front',151.0,230.0,true,'upper','abdomen');
perform public.catalogue_upsert_point('GB27','gallbladder',27,'Wu Shu','五枢','Fifth Pivot','front',149.0,250.0,true,'upper','abdomen');
perform public.catalogue_upsert_point('GB28','gallbladder',28,'Wei Dao','维道','Linking Path','front',148.0,258.0,true,'upper','abdomen');
perform public.catalogue_upsert_point('GB29','gallbladder',29,'Ju Liao','居髎','Squatting Bone-Hole','front',149.0,282.5,true,'lower','abdomen');
perform public.catalogue_upsert_point('GB30','gallbladder',30,'Huan Tiao','环跳','Jumping Round','back',150.0,299.0,true,'lower','hip');
perform public.catalogue_upsert_point('GB31','gallbladder',31,'Feng Shi','风市','Wind Market','front',148.0,322.0,true,'lower','thigh');
perform public.catalogue_upsert_point('GB32','gallbladder',32,'Zhong Du','中渎','Central River','front',146.0,360.0,true,'lower','thigh');
perform public.catalogue_upsert_point('GB33','gallbladder',33,'Xi Yang Guan','膝阳关','Knee Yang Joint','front',144.0,391.0,true,'lower','thigh');
perform public.catalogue_upsert_point('GB34','gallbladder',34,'Yang Ling Quan','阳陵泉','Yang Mound Spring','front',144.0,417.0,true,'lower','knee');
perform public.catalogue_upsert_point('GB35','gallbladder',35,'Yang Jiao','阳交','Yang Intersection','front',143.0,447.0,true,'lower','lower_leg');
perform public.catalogue_upsert_point('GB36','gallbladder',36,'Wai Qiu','外丘','Outer Mound','front',143.0,457.0,true,'lower','lower_leg');
perform public.catalogue_upsert_point('GB37','gallbladder',37,'Guang Ming','光明','Bright Light','front',142.0,474.5,true,'lower','lower_leg');
perform public.catalogue_upsert_point('GB38','gallbladder',38,'Yang Fu','阳辅','Yang Assistance','front',141.0,498.0,true,'lower','lower_leg');
perform public.catalogue_upsert_point('GB39','gallbladder',39,'Xuan Zhong','悬钟','Suspended Bell','front',141.0,510.0,true,'lower','lower_leg');
perform public.catalogue_upsert_point('GB40','gallbladder',40,'Qiu Xu','丘墟','Mound of Ruins','front',140.0,524.0,true,'lower','ankle');
perform public.catalogue_upsert_point('GB41','gallbladder',41,'Zu Lin Qi','足临泣','Foot Overlooking Tears','front',139.0,535.0,true,'lower','foot');
perform public.catalogue_upsert_point('GB42','gallbladder',42,'Di Wu Hui','地五会','Earth Fivefold Convergence','front',139.0,539.0,true,'lower','foot');
perform public.catalogue_upsert_point('GB43','gallbladder',43,'Xia Xi','侠溪','Pinched Ravine','front',138.0,543.0,true,'lower','foot');
perform public.catalogue_upsert_point('GB44','gallbladder',44,'Zu Qiao Yin','足窍阴','Foot Portal Yin','front',138.0,547.0,true,'lower','foot');
-- LR · liver
perform public.catalogue_upsert_point('LR1','liver',1,'Da Dun','大敦','Large Pile','front',132.0,545.0,true,'lower','foot');
perform public.catalogue_upsert_point('LR2','liver',2,'Xing Jian','行间','Moving Between','front',126.5,516.3,true,'lower','foot');
perform public.catalogue_upsert_point('LR3','liver',3,'Tai Chong','太冲','Supreme Rush','front',124.5,487.0,true,'lower','foot');
perform public.catalogue_upsert_point('LR4','liver',4,'Zhong Feng','中封','Mound Centre','front',123.0,457.6,true,'lower','ankle');
perform public.catalogue_upsert_point('LR5','liver',5,'Li Gou','蠡沟','Woodworm Canal','front',123.3,428.3,true,'lower','lower_leg');
perform public.catalogue_upsert_point('LR6','liver',6,'Zhong Du','中都','Central Metropolis','front',126.4,399.1,true,'lower','lower_leg');
perform public.catalogue_upsert_point('LR7','liver',7,'Xi Guan','膝关','Knee Joint','front',128.2,369.7,true,'lower','knee');
perform public.catalogue_upsert_point('LR8','liver',8,'Qu Quan','曲泉','Spring at the Bend','front',130.2,340.4,true,'lower','knee');
perform public.catalogue_upsert_point('LR9','liver',9,'Yin Bao','阴包','Yin Bladder','front',133.8,311.3,true,'lower','thigh');
perform public.catalogue_upsert_point('LR10','liver',10,'Zu Wu Li','足五里','Leg Five Li','front',138.6,282.3,true,'lower','thigh');
perform public.catalogue_upsert_point('LR11','liver',11,'Yin Lian','阴廉','Yin Corner','front',143.8,253.4,true,'lower','thigh');
perform public.catalogue_upsert_point('LR12','liver',12,'Ji Mai','急脉','Urgent Pulse','front',148.5,224.4,true,'lower','hip');
perform public.catalogue_upsert_point('LR13','liver',13,'Zhang Men','章门','Camphorwood Gate','front',151.6,195.3,true,'upper','abdomen');
perform public.catalogue_upsert_point('LR14','liver',14,'Qi Men','期门','Cycle Gate','front',150.0,166.0,true,'upper','abdomen');
-- REN · ren
perform public.catalogue_upsert_point('REN1','ren',1,'Hui Yin','会阴','Meeting of Yin','front',110.0,288.5,false,'center','abdomen');
perform public.catalogue_upsert_point('REN2','ren',2,'Qu Gu','曲骨','Curved Bone','front',110.0,282.5,false,'center','abdomen');
perform public.catalogue_upsert_point('REN3','ren',3,'Zhong Ji','中极','Central Pole','front',110.0,272.5,false,'center','abdomen');
perform public.catalogue_upsert_point('REN4','ren',4,'Guan Yuan','关元','Origin Pass','front',110.0,258.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN5','ren',5,'Shi Men','石门','Stone Gate','front',110.0,250.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN6','ren',6,'Qi Hai','气海','Sea of Qi','front',110.0,244.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN7','ren',7,'Yin Jiao','阴交','Yin Intersection','front',110.0,238.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN8','ren',8,'Shen Que','神阙','Spirit Gate Tower','front',110.0,230.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN9','ren',9,'Shui Fen','水分','Water Divide','front',110.0,220.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN10','ren',10,'Xia Wan','下脘','Lower Venter','front',110.0,212.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN11','ren',11,'Jian Li','建里','Interior Strengthening','front',110.0,214.4,false,'center','abdomen');
perform public.catalogue_upsert_point('REN12','ren',12,'Zhong Wan','中脘','Central Venter','front',110.0,204.4,false,'center','abdomen');
perform public.catalogue_upsert_point('REN13','ren',13,'Shang Wan','上脘','Upper Venter','front',110.0,195.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN14','ren',14,'Ju Que','巨阙','Great Tower Gate','front',110.0,185.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN15','ren',15,'Jiu Wei','鸠尾','Turtledove Tail','front',110.0,177.0,false,'center','abdomen');
perform public.catalogue_upsert_point('REN16','ren',16,'Zhong Ting','中庭','Central Courtyard','front',110.0,174.0,false,'center','chest');
perform public.catalogue_upsert_point('REN17','ren',17,'Shan Zhong','膻中','Chest Centre','front',110.0,160.0,false,'center','chest');
perform public.catalogue_upsert_point('REN18','ren',18,'Yu Tang','玉堂','Jade Hall','front',110.0,146.0,false,'center','chest');
perform public.catalogue_upsert_point('REN19','ren',19,'Zi Gong','紫宫','Purple Palace','front',110.0,136.0,false,'center','chest');
perform public.catalogue_upsert_point('REN20','ren',20,'Hua Gai','华盖','Florid Canopy','front',110.0,129.9,false,'center','chest');
perform public.catalogue_upsert_point('REN21','ren',21,'Xuan Ji','璇玑','Jade Pivot','front',110.0,119.9,false,'center','chest');
perform public.catalogue_upsert_point('REN22','ren',22,'Tian Tu','天突','Celestial Chimney','front',110.0,109.9,false,'center','neck');
perform public.catalogue_upsert_point('REN23','ren',23,'Lian Quan','廉泉','Ridge Spring','front',110.0,92.5,false,'center','neck');
perform public.catalogue_upsert_point('REN24','ren',24,'Cheng Jiang','承浆','Sauce Receptacle','front',110.0,92.0,false,'center','face');
-- DU · du
perform public.catalogue_upsert_point('DU1','du',1,'Chang Qiang','长强','Long Strong','back',110.0,307.0,false,'center','sacrum');
perform public.catalogue_upsert_point('DU2','du',2,'Yao Shu','腰俞','Lumbar Shu','back',110.0,292.5,false,'center','lower_back');
perform public.catalogue_upsert_point('DU3','du',3,'Yao Yang Guan','腰阳关','Lumbar Yang Pass','back',110.0,264.0,false,'center','lower_back');
perform public.catalogue_upsert_point('DU4','du',4,'Ming Men','命门','Life Gate','back',110.0,240.0,false,'center','lower_back');
perform public.catalogue_upsert_point('DU5','du',5,'Xuan Shu','悬枢','Suspended Pivot','back',110.0,230.0,false,'center','upper_back');
perform public.catalogue_upsert_point('DU6','du',6,'Ji Zhong','脊中','Spinal Centre','back',110.0,218.0,false,'center','upper_back');
perform public.catalogue_upsert_point('DU7','du',7,'Zhong Shu','中枢','Central Pivot','back',110.0,206.4,false,'center','upper_back');
perform public.catalogue_upsert_point('DU8','du',8,'Jin Suo','筋缩','Sinew Contraction','back',110.0,191.0,false,'center','upper_back');
perform public.catalogue_upsert_point('DU9','du',9,'Zhi Yang','至阳','Reaching Yang','back',110.0,179.0,false,'center','upper_back');
perform public.catalogue_upsert_point('DU10','du',10,'Ling Tai','灵台','Spirit Tower','back',110.0,176.0,false,'center','upper_back');
perform public.catalogue_upsert_point('DU11','du',11,'Shen Dao','神道','Spirit Pathway','back',110.0,164.0,false,'center','upper_back');
perform public.catalogue_upsert_point('DU12','du',12,'Shen Zhu','身柱','Body Pillar','back',110.0,150.0,false,'center','upper_back');
perform public.catalogue_upsert_point('DU13','du',13,'Tao Dao','陶道','Kiln Path','back',110.0,123.9,false,'center','upper_back');
perform public.catalogue_upsert_point('DU14','du',14,'Da Zhui','大椎','Great Hammer','back',110.0,111.9,false,'center','neck');
perform public.catalogue_upsert_point('DU15','du',15,'Ya Men','哑门','Mute Gate','back',110.0,94.5,false,'center','neck');
perform public.catalogue_upsert_point('DU16','du',16,'Feng Fu','风府','Wind Mansion','back',110.0,86.5,false,'center','neck');
perform public.catalogue_upsert_point('DU17','du',17,'Nao Hu','脑户','Brain Door','back',110.0,61.0,false,'center','head');
perform public.catalogue_upsert_point('DU18','du',18,'Qiang Jian','强间','Unyielding Space','back',110.0,52.1,false,'center','head');
perform public.catalogue_upsert_point('DU19','du',19,'Hou Ding','后顶','Behind the Vertex','back',110.0,36.1,false,'center','head');
perform public.catalogue_upsert_point('DU20','du',20,'Bai Hui','百会','Hundred Convergences','back',110.0,22.1,false,'center','head');
perform public.catalogue_upsert_point('DU21','du',21,'Qian Ding','前顶','Before the Vertex','front',110.0,26.1,false,'center','head');
perform public.catalogue_upsert_point('DU22','du',22,'Xin Hui','囟会','Fontanel Meeting','front',110.0,34.1,false,'center','head');
perform public.catalogue_upsert_point('DU23','du',23,'Shang Xing','上星','Upper Star','front',110.0,44.1,false,'center','head');
perform public.catalogue_upsert_point('DU24','du',24,'Shen Ting','神庭','Spirit Court','front',110.0,52.1,false,'center','head');
perform public.catalogue_upsert_point('DU25','du',25,'Su Liao','素髎','White Bone-Hole','front',110.0,70.4,false,'center','face');
perform public.catalogue_upsert_point('DU26','du',26,'Shui Gou','水沟','Water Trough','front',110.0,78.4,false,'center','face');
perform public.catalogue_upsert_point('DU27','du',27,'Dui Duan','兑端','Extremity of the Mouth','front',110.0,79.5,false,'center','face');
perform public.catalogue_upsert_point('DU28','du',28,'Yin Jiao','龈交','Gum Intersection','front',110.0,84.5,false,'center','face');

end
$seed$;
