-- ============================================================================
-- Acupuncture point catalogue · the 361 points of the fourteen channels
-- ============================================================================
-- Generated. Coordinates are schematic positions on the body diagram the app
-- draws (200 wide, 520 tall, midline at x = 100); a bilateral point is mirrored
-- by the renderer. They show which points a treatment used and roughly where —
-- they are not an anatomical locator and must not be used as one.
--
-- Clinical text (location, actions, indications, needling, cautions) is left
-- empty on purpose: the columns exist so filling them in later is data entry.
-- Every row is flagged needs_review until a practitioner confirms it.
-- ============================================================================

do $seed$
begin

-- LU · lung
perform public.upsert_acupuncture_point('LU1','lung',1,'Zhong Fu','中府','Central Treasury','front',138.0,100.0,true,'upper');
perform public.upsert_acupuncture_point('LU2','lung',2,'Yun Men','云门','Cloud Gate','front',141.9,118.9,true,'upper');
perform public.upsert_acupuncture_point('LU3','lung',3,'Tian Fu','天府','Celestial Storehouse','front',147.1,137.6,true,'upper');
perform public.upsert_acupuncture_point('LU4','lung',4,'Xia Bai','侠白','Guarding White','front',152.1,156.3,true,'upper');
perform public.upsert_acupuncture_point('LU5','lung',5,'Chi Ze','尺泽','Cubit Marsh','front',156.8,175.1,true,'upper');
perform public.upsert_acupuncture_point('LU6','lung',6,'Kong Zui','孔最','Collection Hole','front',161.5,193.9,true,'upper');
perform public.upsert_acupuncture_point('LU7','lung',7,'Lie Que','列缺','Broken Sequence','front',166.2,212.7,true,'upper');
perform public.upsert_acupuncture_point('LU8','lung',8,'Jing Qu','经渠','Channel Ditch','front',171.0,231.4,true,'upper');
perform public.upsert_acupuncture_point('LU9','lung',9,'Tai Yuan','太渊','Great Abyss','front',176.3,250.1,true,'upper');
perform public.upsert_acupuncture_point('LU10','lung',10,'Yu Ji','鱼际','Fish Border','front',179.5,269.2,true,'upper');
perform public.upsert_acupuncture_point('LU11','lung',11,'Shao Shang','少商','Lesser Shang','front',184.0,288.0,true,'upper');
-- LI · large_intestine
perform public.upsert_acupuncture_point('LI1','large_intestine',1,'Shang Yang','商阳','Shang Yang','front',186.0,292.0,true,'upper');
perform public.upsert_acupuncture_point('LI2','large_intestine',2,'Er Jian','二间','Second Space','front',182.8,279.1,true,'upper');
perform public.upsert_acupuncture_point('LI3','large_intestine',3,'San Jian','三间','Third Space','front',179.7,266.1,true,'upper');
perform public.upsert_acupuncture_point('LI4','large_intestine',4,'He Gu','合谷','Joining Valley','front',176.7,253.1,true,'upper');
perform public.upsert_acupuncture_point('LI5','large_intestine',5,'Yang Xi','阳溪','Yang Ravine','front',173.2,240.2,true,'upper');
perform public.upsert_acupuncture_point('LI6','large_intestine',6,'Pian Li','偏历','Veering Passage','front',170.2,227.2,true,'upper');
perform public.upsert_acupuncture_point('LI7','large_intestine',7,'Wen Liu','温溜','Warm Dwelling','front',167.6,214.1,true,'upper');
perform public.upsert_acupuncture_point('LI8','large_intestine',8,'Xia Lian','下廉','Lower Ridge','front',165.0,201.0,true,'upper');
perform public.upsert_acupuncture_point('LI9','large_intestine',9,'Shang Lian','上廉','Upper Ridge','front',162.4,187.9,true,'upper');
perform public.upsert_acupuncture_point('LI10','large_intestine',10,'Shou San Li','手三里','Arm Three Li','front',160.4,174.7,true,'upper');
perform public.upsert_acupuncture_point('LI11','large_intestine',11,'Qu Chi','曲池','Pool at the Bend','front',158.5,161.5,true,'upper');
perform public.upsert_acupuncture_point('LI12','large_intestine',12,'Zhou Liao','肘髎','Elbow Bone-Hole','front',156.6,148.3,true,'upper');
perform public.upsert_acupuncture_point('LI13','large_intestine',13,'Shou Wu Li','手五里','Arm Five Li','front',154.7,135.1,true,'upper');
perform public.upsert_acupuncture_point('LI14','large_intestine',14,'Bi Nao','臂臑','Upper Arm','front',151.8,122.1,true,'upper');
perform public.upsert_acupuncture_point('LI15','large_intestine',15,'Jian Yu','肩髃','Shoulder Bone','front',148.3,109.2,true,'upper');
perform public.upsert_acupuncture_point('LI16','large_intestine',16,'Ju Gu','巨骨','Great Bone','front',141.8,97.6,true,'upper');
perform public.upsert_acupuncture_point('LI17','large_intestine',17,'Tian Ding','天鼎','Celestial Vessel','front',134.9,86.2,true,'upper');
perform public.upsert_acupuncture_point('LI18','large_intestine',18,'Fu Tu','扶突','Protuberance Assistant','front',128.0,74.7,true,'upper');
perform public.upsert_acupuncture_point('LI19','large_intestine',19,'Kou He Liao','口禾髎','Mouth Grain Bone-Hole','front',121.0,63.4,true,'upper');
perform public.upsert_acupuncture_point('LI20','large_intestine',20,'Ying Xiang','迎香','Welcome Fragrance','front',114.0,52.0,true,'upper');
-- ST · stomach
perform public.upsert_acupuncture_point('ST1','stomach',1,'Cheng Qi','承泣','Tear Container','front',113.0,40.0,true,'upper');
perform public.upsert_acupuncture_point('ST2','stomach',2,'Si Bai','四白','Four Whites','front',114.9,50.2,true,'upper');
perform public.upsert_acupuncture_point('ST3','stomach',3,'Ju Liao','巨髎','Great Bone-Hole','front',116.9,60.5,true,'upper');
perform public.upsert_acupuncture_point('ST4','stomach',4,'Di Cang','地仓','Earth Granary','front',116.3,70.5,true,'upper');
perform public.upsert_acupuncture_point('ST5','stomach',5,'Da Ying','大迎','Great Reception','front',117.0,80.4,true,'upper');
perform public.upsert_acupuncture_point('ST6','stomach',6,'Jia Che','颊车','Jaw Bone','front',120.0,90.3,true,'upper');
perform public.upsert_acupuncture_point('ST7','stomach',7,'Xia Guan','下关','Below the Joint','front',118.7,100.7,true,'upper');
perform public.upsert_acupuncture_point('ST8','stomach',8,'Tou Wei','头维','Head Corner','front',117.8,111.0,true,'upper');
perform public.upsert_acupuncture_point('ST9','stomach',9,'Ren Ying','人迎','Man Welcome','front',117.3,121.5,true,'upper');
perform public.upsert_acupuncture_point('ST10','stomach',10,'Shui Tu','水突','Water Prominence','front',116.8,131.9,true,'upper');
perform public.upsert_acupuncture_point('ST11','stomach',11,'Qi She','气舍','Qi Abode','front',116.4,142.3,true,'upper');
perform public.upsert_acupuncture_point('ST12','stomach',12,'Que Pen','缺盆','Empty Basin','front',115.9,152.7,true,'upper');
perform public.upsert_acupuncture_point('ST13','stomach',13,'Qi Hu','气户','Qi Door','front',115.5,163.1,true,'upper');
perform public.upsert_acupuncture_point('ST14','stomach',14,'Ku Fang','库房','Storeroom','front',115.2,173.5,true,'upper');
perform public.upsert_acupuncture_point('ST15','stomach',15,'Wu Yi','屋翳','Roof','front',114.8,183.9,true,'upper');
perform public.upsert_acupuncture_point('ST16','stomach',16,'Ying Chuang','膺窗','Breast Window','front',114.5,194.4,true,'upper');
perform public.upsert_acupuncture_point('ST17','stomach',17,'Ru Zhong','乳中','Breast Centre','front',114.1,204.8,true,'upper');
perform public.upsert_acupuncture_point('ST18','stomach',18,'Ru Gen','乳根','Breast Root','front',115.1,215.1,true,'upper');
perform public.upsert_acupuncture_point('ST19','stomach',19,'Bu Rong','不容','Not Contained','front',116.7,225.4,true,'upper');
perform public.upsert_acupuncture_point('ST20','stomach',20,'Cheng Man','承满','Assuming Fullness','front',118.4,235.7,true,'upper');
perform public.upsert_acupuncture_point('ST21','stomach',21,'Liang Men','梁门','Beam Gate','front',120.0,246.0,true,'upper');
perform public.upsert_acupuncture_point('ST22','stomach',22,'Guan Men','关门','Pass Gate','front',120.4,256.4,true,'upper');
perform public.upsert_acupuncture_point('ST23','stomach',23,'Tai Yi','太乙','Supreme Unity','front',120.8,266.8,true,'upper');
perform public.upsert_acupuncture_point('ST24','stomach',24,'Hua Rou Men','滑肉门','Slippery Flesh Gate','front',121.2,277.2,true,'upper');
perform public.upsert_acupuncture_point('ST25','stomach',25,'Tian Shu','天枢','Celestial Pivot','front',121.5,287.7,true,'upper');
perform public.upsert_acupuncture_point('ST26','stomach',26,'Wai Ling','外陵','Outer Mound','front',121.9,298.1,true,'upper');
perform public.upsert_acupuncture_point('ST27','stomach',27,'Da Ju','大巨','Great Gigantic','front',122.2,308.5,true,'upper');
perform public.upsert_acupuncture_point('ST28','stomach',28,'Shui Dao','水道','Water Passage','front',122.5,318.9,true,'upper');
perform public.upsert_acupuncture_point('ST29','stomach',29,'Gui Lai','归来','Return','front',122.8,329.3,true,'upper');
perform public.upsert_acupuncture_point('ST30','stomach',30,'Qi Chong','气冲','Rushing Qi','front',123.1,339.7,true,'upper');
perform public.upsert_acupuncture_point('ST31','stomach',31,'Bi Guan','髀关','Thigh Joint','front',123.4,350.2,true,'lower');
perform public.upsert_acupuncture_point('ST32','stomach',32,'Fu Tu','伏兔','Crouching Rabbit','front',123.7,360.6,true,'lower');
perform public.upsert_acupuncture_point('ST33','stomach',33,'Yin Shi','阴市','Yin Market','front',124.0,371.0,true,'lower');
perform public.upsert_acupuncture_point('ST34','stomach',34,'Liang Qiu','梁丘','Ridge Mound','front',124.0,381.4,true,'lower');
perform public.upsert_acupuncture_point('ST35','stomach',35,'Du Bi','犊鼻','Calf''s Nose','front',124.0,391.9,true,'lower');
perform public.upsert_acupuncture_point('ST36','stomach',36,'Zu San Li','足三里','Leg Three Li','front',124.0,402.3,true,'lower');
perform public.upsert_acupuncture_point('ST37','stomach',37,'Shang Ju Xu','上巨虚','Upper Great Hollow','front',124.0,412.7,true,'lower');
perform public.upsert_acupuncture_point('ST38','stomach',38,'Tiao Kou','条口','Ribbon Opening','front',123.8,423.1,true,'lower');
perform public.upsert_acupuncture_point('ST39','stomach',39,'Xia Ju Xu','下巨虚','Lower Great Hollow','front',123.2,433.5,true,'lower');
perform public.upsert_acupuncture_point('ST40','stomach',40,'Feng Long','丰隆','Bountiful Bulge','front',122.7,443.9,true,'lower');
perform public.upsert_acupuncture_point('ST41','stomach',41,'Jie Xi','解溪','Ravine Divide','front',122.1,454.3,true,'lower');
perform public.upsert_acupuncture_point('ST42','stomach',42,'Chong Yang','冲阳','Surging Yang','front',121.6,464.7,true,'lower');
perform public.upsert_acupuncture_point('ST43','stomach',43,'Xian Gu','陷谷','Sunken Valley','front',121.1,475.2,true,'lower');
perform public.upsert_acupuncture_point('ST44','stomach',44,'Nei Ting','内庭','Inner Court','front',121.0,485.6,true,'lower');
perform public.upsert_acupuncture_point('ST45','stomach',45,'Li Dui','厉兑','Severe Mouth','front',121.0,496.0,true,'lower');
-- SP · spleen
perform public.upsert_acupuncture_point('SP1','spleen',1,'Yin Bai','隐白','Hidden White','front',118.0,498.0,true,'lower');
perform public.upsert_acupuncture_point('SP2','spleen',2,'Da Du','大都','Great Metropolis','front',115.7,478.1,true,'lower');
perform public.upsert_acupuncture_point('SP3','spleen',3,'Tai Bai','太白','Supreme White','front',112.9,458.3,true,'lower');
perform public.upsert_acupuncture_point('SP4','spleen',4,'Gong Sun','公孙','Yellow Emperor','front',112.3,438.3,true,'lower');
perform public.upsert_acupuncture_point('SP5','spleen',5,'Shang Qiu','商丘','Shang Hill','front',112.4,418.3,true,'lower');
perform public.upsert_acupuncture_point('SP6','spleen',6,'San Yin Jiao','三阴交','Three Yin Intersection','front',113.1,398.2,true,'lower');
perform public.upsert_acupuncture_point('SP7','spleen',7,'Lou Gu','漏谷','Leaking Valley','front',114.3,378.2,true,'lower');
perform public.upsert_acupuncture_point('SP8','spleen',8,'Di Ji','地机','Earth Pivot','front',115.4,358.2,true,'lower');
perform public.upsert_acupuncture_point('SP9','spleen',9,'Yin Ling Quan','阴陵泉','Yin Mound Spring','front',116.6,338.2,true,'lower');
perform public.upsert_acupuncture_point('SP10','spleen',10,'Xue Hai','血海','Sea of Blood','front',117.9,318.3,true,'lower');
perform public.upsert_acupuncture_point('SP11','spleen',11,'Ji Men','箕门','Winnower Gate','front',119.1,298.3,true,'lower');
perform public.upsert_acupuncture_point('SP12','spleen',12,'Chong Men','冲门','Surging Gate','front',120.8,278.3,true,'upper');
perform public.upsert_acupuncture_point('SP13','spleen',13,'Fu She','府舍','Bowel Abode','front',122.5,258.3,true,'upper');
perform public.upsert_acupuncture_point('SP14','spleen',14,'Fu Jie','腹结','Abdominal Bind','front',124.2,238.4,true,'upper');
perform public.upsert_acupuncture_point('SP15','spleen',15,'Da Heng','大横','Great Horizontal','front',126.5,218.5,true,'upper');
perform public.upsert_acupuncture_point('SP16','spleen',16,'Fu Ai','腹哀','Abdominal Lament','front',128.9,198.6,true,'upper');
perform public.upsert_acupuncture_point('SP17','spleen',17,'Shi Dou','食窦','Food Hole','front',130.4,178.6,true,'upper');
perform public.upsert_acupuncture_point('SP18','spleen',18,'Tian Xi','天溪','Celestial Ravine','front',131.2,158.6,true,'upper');
perform public.upsert_acupuncture_point('SP19','spleen',19,'Xiong Xiang','胸乡','Chest Village','front',134.3,138.9,true,'upper');
perform public.upsert_acupuncture_point('SP20','spleen',20,'Zhou Rong','周荣','Encircling Glory','front',139.6,119.5,true,'upper');
perform public.upsert_acupuncture_point('SP21','spleen',21,'Da Bao','大包','Great Embracement','front',144.0,100.0,true,'upper');
-- HT · heart
perform public.upsert_acupuncture_point('HT1','heart',1,'Ji Quan','极泉','Highest Spring','front',144.0,102.0,true,'upper');
perform public.upsert_acupuncture_point('HT2','heart',2,'Qing Ling','青灵','Green Spirit','front',148.1,125.6,true,'upper');
perform public.upsert_acupuncture_point('HT3','heart',3,'Shao Hai','少海','Lesser Sea','front',152.3,149.2,true,'upper');
perform public.upsert_acupuncture_point('HT4','heart',4,'Ling Dao','灵道','Spirit Pathway','front',158.1,172.5,true,'upper');
perform public.upsert_acupuncture_point('HT5','heart',5,'Tong Li','通里','Connecting Li','front',163.2,195.9,true,'upper');
perform public.upsert_acupuncture_point('HT6','heart',6,'Yin Xi','阴郄','Yin Cleft','front',167.5,219.5,true,'upper');
perform public.upsert_acupuncture_point('HT7','heart',7,'Shen Men','神门','Spirit Gate','front',172.0,243.1,true,'upper');
perform public.upsert_acupuncture_point('HT8','heart',8,'Shao Fu','少府','Lesser Mansion','front',176.7,266.6,true,'upper');
perform public.upsert_acupuncture_point('HT9','heart',9,'Shao Chong','少冲','Lesser Surge','front',182.0,290.0,true,'upper');
-- SI · small_intestine
perform public.upsert_acupuncture_point('SI1','small_intestine',1,'Shao Ze','少泽','Lesser Marsh','back',184.0,290.0,true,'upper');
perform public.upsert_acupuncture_point('SI2','small_intestine',2,'Qian Gu','前谷','Front Valley','back',181.6,276.5,true,'upper');
perform public.upsert_acupuncture_point('SI3','small_intestine',3,'Hou Xi','后溪','Back Ravine','back',179.2,263.1,true,'upper');
perform public.upsert_acupuncture_point('SI4','small_intestine',4,'Wan Gu','腕骨','Wrist Bone','back',176.9,249.6,true,'upper');
perform public.upsert_acupuncture_point('SI5','small_intestine',5,'Yang Gu','阳谷','Yang Valley','back',174.1,236.2,true,'upper');
perform public.upsert_acupuncture_point('SI6','small_intestine',6,'Yang Lao','养老','Nursing the Aged','back',171.5,222.7,true,'upper');
perform public.upsert_acupuncture_point('SI7','small_intestine',7,'Zhi Zheng','支正','Branch to the Correct','back',169.3,209.2,true,'upper');
perform public.upsert_acupuncture_point('SI8','small_intestine',8,'Xiao Hai','小海','Small Sea','back',167.2,195.7,true,'upper');
perform public.upsert_acupuncture_point('SI9','small_intestine',9,'Jian Zhen','肩贞','True Shoulder','back',164.6,182.3,true,'upper');
perform public.upsert_acupuncture_point('SI10','small_intestine',10,'Nao Shu','臑俞','Upper Arm Shu','back',161.5,168.9,true,'upper');
perform public.upsert_acupuncture_point('SI11','small_intestine',11,'Tian Zong','天宗','Celestial Gathering','back',158.3,155.6,true,'upper');
perform public.upsert_acupuncture_point('SI12','small_intestine',12,'Bing Feng','秉风','Grasping the Wind','back',155.1,142.3,true,'upper');
perform public.upsert_acupuncture_point('SI13','small_intestine',13,'Qu Yuan','曲垣','Crooked Wall','back',151.8,129.1,true,'upper');
perform public.upsert_acupuncture_point('SI14','small_intestine',14,'Jian Wai Shu','肩外俞','Outer Shoulder Shu','back',148.3,115.8,true,'upper');
perform public.upsert_acupuncture_point('SI15','small_intestine',15,'Jian Zhong Shu','肩中俞','Middle Shoulder Shu','back',144.7,102.6,true,'upper');
perform public.upsert_acupuncture_point('SI16','small_intestine',16,'Tian Chuang','天窗','Celestial Window','back',139.4,90.0,true,'upper');
perform public.upsert_acupuncture_point('SI17','small_intestine',17,'Tian Rong','天容','Celestial Countenance','back',133.7,77.6,true,'upper');
perform public.upsert_acupuncture_point('SI18','small_intestine',18,'Quan Liao','颧髎','Cheek Bone-Hole','back',128.7,64.9,true,'upper');
perform public.upsert_acupuncture_point('SI19','small_intestine',19,'Ting Gong','听宫','Auditory Palace','back',124.0,52.0,true,'upper');
-- BL · bladder
perform public.upsert_acupuncture_point('BL1','bladder',1,'Jing Ming','睛明','Bright Eyes','front',110.0,40.0,true,'upper');
perform public.upsert_acupuncture_point('BL2','bladder',2,'Zan Zhu','攒竹','Gathered Bamboo','front',113.0,34.0,true,'upper');
perform public.upsert_acupuncture_point('BL3','bladder',3,'Mei Chong','眉冲','Eyebrow Ascension','back',112.0,26.0,true,'upper');
perform public.upsert_acupuncture_point('BL4','bladder',4,'Qu Cha','曲差','Deviating Turn','back',115.0,24.0,true,'upper');
perform public.upsert_acupuncture_point('BL5','bladder',5,'Wu Chu','五处','Fifth Place','back',115.0,22.0,true,'upper');
perform public.upsert_acupuncture_point('BL6','bladder',6,'Cheng Guang','承光','Receiving Light','back',115.0,24.0,true,'upper');
perform public.upsert_acupuncture_point('BL7','bladder',7,'Tong Tian','通天','Celestial Connection','back',114.0,28.0,true,'upper');
perform public.upsert_acupuncture_point('BL8','bladder',8,'Luo Que','络却','Declining Connection','back',114.0,36.0,true,'upper');
perform public.upsert_acupuncture_point('BL9','bladder',9,'Yu Zhen','玉枕','Jade Pillow','back',113.0,52.0,true,'upper');
perform public.upsert_acupuncture_point('BL10','bladder',10,'Tian Zhu','天柱','Celestial Pillar','back',113.0,68.0,true,'upper');
perform public.upsert_acupuncture_point('BL11','bladder',11,'Da Zhu','大杼','Great Shuttle','back',112.0,88.0,true,'upper');
perform public.upsert_acupuncture_point('BL12','bladder',12,'Feng Men','风门','Wind Gate','back',112.0,94.2,true,'upper');
perform public.upsert_acupuncture_point('BL13','bladder',13,'Fei Shu','肺俞','Lung Shu','back',112.0,100.4,true,'upper');
perform public.upsert_acupuncture_point('BL14','bladder',14,'Jue Yin Shu','厥阴俞','Jue Yin Shu','back',112.0,106.6,true,'upper');
perform public.upsert_acupuncture_point('BL15','bladder',15,'Xin Shu','心俞','Heart Shu','back',112.0,112.8,true,'upper');
perform public.upsert_acupuncture_point('BL16','bladder',16,'Du Shu','督俞','Governing Shu','back',112.0,119.1,true,'upper');
perform public.upsert_acupuncture_point('BL17','bladder',17,'Ge Shu','膈俞','Diaphragm Shu','back',112.0,125.3,true,'upper');
perform public.upsert_acupuncture_point('BL18','bladder',18,'Gan Shu','肝俞','Liver Shu','back',112.0,131.5,true,'upper');
perform public.upsert_acupuncture_point('BL19','bladder',19,'Dan Shu','胆俞','Gallbladder Shu','back',112.0,137.7,true,'upper');
perform public.upsert_acupuncture_point('BL20','bladder',20,'Pi Shu','脾俞','Spleen Shu','back',112.0,143.9,true,'upper');
perform public.upsert_acupuncture_point('BL21','bladder',21,'Wei Shu','胃俞','Stomach Shu','back',112.0,150.1,true,'upper');
perform public.upsert_acupuncture_point('BL22','bladder',22,'San Jiao Shu','三焦俞','Triple Burner Shu','back',112.0,156.3,true,'upper');
perform public.upsert_acupuncture_point('BL23','bladder',23,'Shen Shu','肾俞','Kidney Shu','back',112.0,162.5,true,'upper');
perform public.upsert_acupuncture_point('BL24','bladder',24,'Qi Hai Shu','气海俞','Sea of Qi Shu','back',112.0,168.7,true,'upper');
perform public.upsert_acupuncture_point('BL25','bladder',25,'Da Chang Shu','大肠俞','Large Intestine Shu','back',112.0,174.9,true,'upper');
perform public.upsert_acupuncture_point('BL26','bladder',26,'Guan Yuan Shu','关元俞','Origin Pass Shu','back',112.0,181.2,true,'upper');
perform public.upsert_acupuncture_point('BL27','bladder',27,'Xiao Chang Shu','小肠俞','Small Intestine Shu','back',112.0,187.4,true,'upper');
perform public.upsert_acupuncture_point('BL28','bladder',28,'Pang Guang Shu','膀胱俞','Bladder Shu','back',112.0,193.6,true,'upper');
perform public.upsert_acupuncture_point('BL29','bladder',29,'Zhong Lu Shu','中膂俞','Central Backbone Shu','back',112.0,199.8,true,'upper');
perform public.upsert_acupuncture_point('BL30','bladder',30,'Bai Huan Shu','白环俞','White Ring Shu','back',112.0,206.0,true,'upper');
perform public.upsert_acupuncture_point('BL31','bladder',31,'Shang Liao','上髎','Upper Bone-Hole','back',108.0,208.0,true,'upper');
perform public.upsert_acupuncture_point('BL32','bladder',32,'Ci Liao','次髎','Second Bone-Hole','back',108.0,216.0,true,'upper');
perform public.upsert_acupuncture_point('BL33','bladder',33,'Zhong Liao','中髎','Central Bone-Hole','back',108.0,224.0,true,'upper');
perform public.upsert_acupuncture_point('BL34','bladder',34,'Xia Liao','下髎','Lower Bone-Hole','back',108.0,232.0,true,'upper');
perform public.upsert_acupuncture_point('BL35','bladder',35,'Hui Yang','会阳','Meeting of Yang','back',112.0,240.0,true,'upper');
perform public.upsert_acupuncture_point('BL36','bladder',36,'Cheng Fu','承扶','Support','back',120.0,250.0,true,'lower');
perform public.upsert_acupuncture_point('BL37','bladder',37,'Yin Men','殷门','Gate of Abundance','back',122.0,292.0,true,'lower');
perform public.upsert_acupuncture_point('BL38','bladder',38,'Fu Xi','浮郄','Superficial Cleft','back',126.0,330.0,true,'lower');
perform public.upsert_acupuncture_point('BL39','bladder',39,'Wei Yang','委阳','Bend Yang','back',127.0,340.0,true,'lower');
perform public.upsert_acupuncture_point('BL40','bladder',40,'Wei Zhong','委中','Bend Middle','back',123.0,344.0,true,'lower');
perform public.upsert_acupuncture_point('BL41','bladder',41,'Fu Fen','附分','Attached Branch','back',126.0,92.0,true,'upper');
perform public.upsert_acupuncture_point('BL42','bladder',42,'Po Hu','魄户','Corporeal Soul Door','back',126.0,103.4,true,'upper');
perform public.upsert_acupuncture_point('BL43','bladder',43,'Gao Huang','膏肓','Vital Region Shu','back',126.0,114.8,true,'upper');
perform public.upsert_acupuncture_point('BL44','bladder',44,'Shen Tang','神堂','Spirit Hall','back',126.0,126.2,true,'upper');
perform public.upsert_acupuncture_point('BL45','bladder',45,'Yi Xi','譩譆','Yi Xi','back',126.0,137.5,true,'upper');
perform public.upsert_acupuncture_point('BL46','bladder',46,'Ge Guan','膈关','Diaphragm Pass','back',126.0,148.9,true,'upper');
perform public.upsert_acupuncture_point('BL47','bladder',47,'Hun Men','魂门','Ethereal Soul Gate','back',126.0,160.3,true,'upper');
perform public.upsert_acupuncture_point('BL48','bladder',48,'Yang Gang','阳纲','Yang Headrope','back',126.0,171.7,true,'upper');
perform public.upsert_acupuncture_point('BL49','bladder',49,'Yi She','意舍','Reflection Abode','back',126.0,183.1,true,'upper');
perform public.upsert_acupuncture_point('BL50','bladder',50,'Wei Cang','胃仓','Stomach Granary','back',126.0,194.5,true,'upper');
perform public.upsert_acupuncture_point('BL51','bladder',51,'Huang Men','肓门','Vitals Gate','back',126.0,205.8,true,'upper');
perform public.upsert_acupuncture_point('BL52','bladder',52,'Zhi Shi','志室','Will Chamber','back',126.0,217.2,true,'upper');
perform public.upsert_acupuncture_point('BL53','bladder',53,'Bao Huang','胞肓','Bladder Vitals','back',126.0,228.6,true,'upper');
perform public.upsert_acupuncture_point('BL54','bladder',54,'Zhi Bian','秩边','Order Limit','back',126.0,240.0,true,'upper');
perform public.upsert_acupuncture_point('BL55','bladder',55,'He Yang','合阳','Yang Union','back',124.0,372.0,true,'lower');
perform public.upsert_acupuncture_point('BL56','bladder',56,'Cheng Jin','承筋','Sinew Support','back',124.0,394.0,true,'lower');
perform public.upsert_acupuncture_point('BL57','bladder',57,'Cheng Shan','承山','Mountain Support','back',124.0,412.0,true,'lower');
perform public.upsert_acupuncture_point('BL58','bladder',58,'Fei Yang','飞扬','Taking Flight','back',126.0,424.0,true,'lower');
perform public.upsert_acupuncture_point('BL59','bladder',59,'Fu Yang','跗阳','Instep Yang','back',126.0,444.0,true,'lower');
perform public.upsert_acupuncture_point('BL60','bladder',60,'Kun Lun','昆仑','Kunlun Mountains','back',127.0,456.0,true,'lower');
perform public.upsert_acupuncture_point('BL61','bladder',61,'Pu Can','仆参','Servant''s Respect','back',127.0,466.0,true,'lower');
perform public.upsert_acupuncture_point('BL62','bladder',62,'Shen Mai','申脉','Extending Vessel','back',127.0,462.0,true,'lower');
perform public.upsert_acupuncture_point('BL63','bladder',63,'Jin Men','金门','Metal Gate','back',127.0,470.0,true,'lower');
perform public.upsert_acupuncture_point('BL64','bladder',64,'Jing Gu','京骨','Capital Bone','back',127.0,478.0,true,'lower');
perform public.upsert_acupuncture_point('BL65','bladder',65,'Shu Gu','束骨','Bundle Bone','back',127.0,486.0,true,'lower');
perform public.upsert_acupuncture_point('BL66','bladder',66,'Zu Tong Gu','足通谷','Valley Passage','back',127.0,492.0,true,'lower');
perform public.upsert_acupuncture_point('BL67','bladder',67,'Zhi Yin','至阴','Reaching Yin','back',127.0,500.0,true,'lower');
-- KI · kidney
perform public.upsert_acupuncture_point('KI1','kidney',1,'Yong Quan','涌泉','Gushing Spring','front',120.0,502.0,true,'lower');
perform public.upsert_acupuncture_point('KI2','kidney',2,'Ran Gu','然谷','Blazing Valley','front',118.5,486.1,true,'lower');
perform public.upsert_acupuncture_point('KI3','kidney',3,'Tai Xi','太溪','Great Ravine','front',117.0,470.2,true,'lower');
perform public.upsert_acupuncture_point('KI4','kidney',4,'Da Zhong','大钟','Large Goblet','front',113.7,454.6,true,'lower');
perform public.upsert_acupuncture_point('KI5','kidney',5,'Shui Quan','水泉','Water Spring','front',112.4,438.7,true,'lower');
perform public.upsert_acupuncture_point('KI6','kidney',6,'Zhao Hai','照海','Shining Sea','front',111.6,422.8,true,'lower');
perform public.upsert_acupuncture_point('KI7','kidney',7,'Fu Liu','复溜','Recover Flow','front',111.2,406.8,true,'lower');
perform public.upsert_acupuncture_point('KI8','kidney',8,'Jiao Xin','交信','Intersection Reach','front',111.6,390.9,true,'lower');
perform public.upsert_acupuncture_point('KI9','kidney',9,'Zhu Bin','筑宾','Guest House','front',112.5,374.9,true,'lower');
perform public.upsert_acupuncture_point('KI10','kidney',10,'Yin Gu','阴谷','Yin Valley','front',113.4,359.0,true,'lower');
perform public.upsert_acupuncture_point('KI11','kidney',11,'Heng Gu','横骨','Pubic Bone','front',113.8,343.0,true,'upper');
perform public.upsert_acupuncture_point('KI12','kidney',12,'Da He','大赫','Great Manifestation','front',113.1,327.1,true,'upper');
perform public.upsert_acupuncture_point('KI13','kidney',13,'Qi Xue','气穴','Qi Hole','front',112.4,311.1,true,'upper');
perform public.upsert_acupuncture_point('KI14','kidney',14,'Si Man','四满','Fourfold Fullness','front',111.7,295.2,true,'upper');
perform public.upsert_acupuncture_point('KI15','kidney',15,'Zhong Zhu','中注','Central Flow','front',111.0,279.2,true,'upper');
perform public.upsert_acupuncture_point('KI16','kidney',16,'Huang Shu','肓俞','Vitals Shu','front',110.3,263.3,true,'upper');
perform public.upsert_acupuncture_point('KI17','kidney',17,'Shang Qu','商曲','Shang Bend','front',109.6,247.3,true,'upper');
perform public.upsert_acupuncture_point('KI18','kidney',18,'Shi Guan','石关','Stone Pass','front',108.9,231.4,true,'upper');
perform public.upsert_acupuncture_point('KI19','kidney',19,'Yin Du','阴都','Yin Metropolis','front',108.2,215.4,true,'upper');
perform public.upsert_acupuncture_point('KI20','kidney',20,'Fu Tong Gu','腹通谷','Abdominal Passage Valley','front',108.0,199.5,true,'upper');
perform public.upsert_acupuncture_point('KI21','kidney',21,'You Men','幽门','Dark Gate','front',108.0,183.5,true,'upper');
perform public.upsert_acupuncture_point('KI22','kidney',22,'Bu Lang','步廊','Corridor Walk','front',108.0,167.5,true,'upper');
perform public.upsert_acupuncture_point('KI23','kidney',23,'Shen Feng','神封','Spirit Seal','front',108.0,151.6,true,'upper');
perform public.upsert_acupuncture_point('KI24','kidney',24,'Ling Xu','灵墟','Spirit Mound','front',109.0,135.6,true,'upper');
perform public.upsert_acupuncture_point('KI25','kidney',25,'Shen Cang','神藏','Spirit Storehouse','front',110.5,119.7,true,'upper');
perform public.upsert_acupuncture_point('KI26','kidney',26,'Yu Zhong','彧中','Lively Centre','front',112.5,103.9,true,'upper');
perform public.upsert_acupuncture_point('KI27','kidney',27,'Shu Fu','俞府','Shu Mansion','front',114.0,88.0,true,'upper');
-- PC · pericardium
perform public.upsert_acupuncture_point('PC1','pericardium',1,'Tian Chi','天池','Celestial Pool','front',144.0,106.0,true,'upper');
perform public.upsert_acupuncture_point('PC2','pericardium',2,'Tian Quan','天泉','Celestial Spring','front',149.1,129.3,true,'upper');
perform public.upsert_acupuncture_point('PC3','pericardium',3,'Qu Ze','曲泽','Marsh at the Bend','front',154.1,152.5,true,'upper');
perform public.upsert_acupuncture_point('PC4','pericardium',4,'Xi Men','郄门','Cleft Gate','front',160.6,175.4,true,'upper');
perform public.upsert_acupuncture_point('PC5','pericardium',5,'Jian Shi','间使','Intermediary Courier','front',165.2,198.7,true,'upper');
perform public.upsert_acupuncture_point('PC6','pericardium',6,'Nei Guan','内关','Inner Pass','front',168.8,222.3,true,'upper');
perform public.upsert_acupuncture_point('PC7','pericardium',7,'Da Ling','大陵','Great Mound','front',173.9,245.5,true,'upper');
perform public.upsert_acupuncture_point('PC8','pericardium',8,'Lao Gong','劳宫','Palace of Toil','front',178.4,268.9,true,'upper');
perform public.upsert_acupuncture_point('PC9','pericardium',9,'Zhong Chong','中冲','Central Hub','front',184.0,292.0,true,'upper');
-- SJ · san_jiao
perform public.upsert_acupuncture_point('SJ1','san_jiao',1,'Guan Chong','关冲','Passage Hub','back',188.0,292.0,true,'upper');
perform public.upsert_acupuncture_point('SJ2','san_jiao',2,'Ye Men','液门','Humour Gate','back',185.5,280.6,true,'upper');
perform public.upsert_acupuncture_point('SJ3','san_jiao',3,'Zhong Zhu','中渚','Central Islet','back',182.8,269.3,true,'upper');
perform public.upsert_acupuncture_point('SJ4','san_jiao',4,'Yang Chi','阳池','Yang Pool','back',180.0,258.0,true,'upper');
perform public.upsert_acupuncture_point('SJ5','san_jiao',5,'Wai Guan','外关','Outer Pass','back',177.5,246.7,true,'upper');
perform public.upsert_acupuncture_point('SJ6','san_jiao',6,'Zhi Gou','支沟','Branch Ditch','back',175.3,235.3,true,'upper');
perform public.upsert_acupuncture_point('SJ7','san_jiao',7,'Hui Zong','会宗','Convergence and Gathering','back',173.6,223.8,true,'upper');
perform public.upsert_acupuncture_point('SJ8','san_jiao',8,'San Yang Luo','三阳络','Three Yang Connection','back',171.8,212.3,true,'upper');
perform public.upsert_acupuncture_point('SJ9','san_jiao',9,'Si Du','四渎','Four Rivers','back',170.1,200.8,true,'upper');
perform public.upsert_acupuncture_point('SJ10','san_jiao',10,'Tian Jing','天井','Celestial Well','back',167.9,189.3,true,'upper');
perform public.upsert_acupuncture_point('SJ11','san_jiao',11,'Qing Leng Yuan','清冷渊','Clear Cold Abyss','back',165.6,177.9,true,'upper');
perform public.upsert_acupuncture_point('SJ12','san_jiao',12,'Xiao Luo','消泺','Dispersing Riverbed','back',163.3,166.5,true,'upper');
perform public.upsert_acupuncture_point('SJ13','san_jiao',13,'Nao Hui','臑会','Upper Arm Convergence','back',161.0,155.1,true,'upper');
perform public.upsert_acupuncture_point('SJ14','san_jiao',14,'Jian Liao','肩髎','Shoulder Bone-Hole','back',158.7,143.7,true,'upper');
perform public.upsert_acupuncture_point('SJ15','san_jiao',15,'Tian Liao','天髎','Celestial Bone-Hole','back',156.5,132.3,true,'upper');
perform public.upsert_acupuncture_point('SJ16','san_jiao',16,'Tian You','天牖','Celestial Window','back',152.9,121.3,true,'upper');
perform public.upsert_acupuncture_point('SJ17','san_jiao',17,'Yi Feng','翳风','Wind Screen','back',149.0,110.3,true,'upper');
perform public.upsert_acupuncture_point('SJ18','san_jiao',18,'Chi Mai','瘛脉','Spasm Vessel','back',145.2,99.3,true,'upper');
perform public.upsert_acupuncture_point('SJ19','san_jiao',19,'Lu Xi','颅息','Skull Rest','back',140.6,88.6,true,'upper');
perform public.upsert_acupuncture_point('SJ20','san_jiao',20,'Jiao Sun','角孙','Angle Vertex','back',135.7,78.1,true,'upper');
perform public.upsert_acupuncture_point('SJ21','san_jiao',21,'Er Men','耳门','Ear Gate','back',130.9,67.5,true,'upper');
perform public.upsert_acupuncture_point('SJ22','san_jiao',22,'Er He Liao','耳和髎','Harmony Bone-Hole','back',126.5,56.7,true,'upper');
perform public.upsert_acupuncture_point('SJ23','san_jiao',23,'Si Zhu Kong','丝竹空','Silk Bamboo Hole','back',122.0,46.0,true,'upper');
-- GB · gallbladder
perform public.upsert_acupuncture_point('GB1','gallbladder',1,'Tong Zi Liao','瞳子髎','Pupil Bone-Hole','front',120.0,42.0,true,'upper');
perform public.upsert_acupuncture_point('GB2','gallbladder',2,'Ting Hui','听会','Auditory Convergence','front',121.0,50.0,true,'upper');
perform public.upsert_acupuncture_point('GB3','gallbladder',3,'Shang Guan','上关','Upper Gate','front',121.0,44.0,true,'upper');
perform public.upsert_acupuncture_point('GB4','gallbladder',4,'Han Yan','颔厌','Jaw Serenity','front',120.0,34.0,true,'upper');
perform public.upsert_acupuncture_point('GB5','gallbladder',5,'Xuan Lu','悬颅','Suspended Skull','front',121.0,38.0,true,'upper');
perform public.upsert_acupuncture_point('GB6','gallbladder',6,'Xuan Li','悬厘','Suspended Tuft','front',121.0,42.0,true,'upper');
perform public.upsert_acupuncture_point('GB7','gallbladder',7,'Qu Bin','曲鬓','Temporal Hairline Curve','front',122.0,46.0,true,'upper');
perform public.upsert_acupuncture_point('GB8','gallbladder',8,'Shuai Gu','率谷','Valley Lead','front',120.0,30.0,true,'upper');
perform public.upsert_acupuncture_point('GB9','gallbladder',9,'Tian Chong','天冲','Celestial Hub','back',120.0,30.0,true,'upper');
perform public.upsert_acupuncture_point('GB10','gallbladder',10,'Fu Bai','浮白','Floating White','back',121.0,40.0,true,'upper');
perform public.upsert_acupuncture_point('GB11','gallbladder',11,'Tou Qiao Yin','头窍阴','Head Portal Yin','back',121.0,48.0,true,'upper');
perform public.upsert_acupuncture_point('GB12','gallbladder',12,'Wan Gu','完骨','Completion Bone','back',119.0,58.0,true,'upper');
perform public.upsert_acupuncture_point('GB13','gallbladder',13,'Ben Shen','本神','Root Spirit','front',115.0,26.0,true,'upper');
perform public.upsert_acupuncture_point('GB14','gallbladder',14,'Yang Bai','阳白','Yang White','front',112.0,36.0,true,'upper');
perform public.upsert_acupuncture_point('GB15','gallbladder',15,'Tou Lin Qi','头临泣','Head Overlooking Tears','back',112.0,24.0,true,'upper');
perform public.upsert_acupuncture_point('GB16','gallbladder',16,'Mu Chuang','目窗','Eye Window','back',113.0,22.0,true,'upper');
perform public.upsert_acupuncture_point('GB17','gallbladder',17,'Zheng Ying','正营','Upright Construction','back',113.0,24.0,true,'upper');
perform public.upsert_acupuncture_point('GB18','gallbladder',18,'Cheng Ling','承灵','Spirit Support','back',113.0,30.0,true,'upper');
perform public.upsert_acupuncture_point('GB19','gallbladder',19,'Nao Kong','脑空','Brain Hollow','back',114.0,44.0,true,'upper');
perform public.upsert_acupuncture_point('GB20','gallbladder',20,'Feng Chi','风池','Wind Pool','back',116.0,62.0,true,'upper');
perform public.upsert_acupuncture_point('GB21','gallbladder',21,'Jian Jing','肩井','Shoulder Well','back',134.0,84.0,true,'upper');
perform public.upsert_acupuncture_point('GB22','gallbladder',22,'Yuan Ye','渊腋','Armpit Abyss','front',144.0,116.0,true,'upper');
perform public.upsert_acupuncture_point('GB23','gallbladder',23,'Zhe Jin','辄筋','Flank Sinews','front',144.0,124.0,true,'upper');
perform public.upsert_acupuncture_point('GB24','gallbladder',24,'Ri Yue','日月','Sun and Moon','front',142.0,142.0,true,'upper');
perform public.upsert_acupuncture_point('GB25','gallbladder',25,'Jing Men','京门','Capital Gate','front',140.0,162.0,true,'upper');
perform public.upsert_acupuncture_point('GB26','gallbladder',26,'Dai Mai','带脉','Girdling Vessel','front',138.0,180.0,true,'upper');
perform public.upsert_acupuncture_point('GB27','gallbladder',27,'Wu Shu','五枢','Fifth Pivot','front',136.0,196.0,true,'upper');
perform public.upsert_acupuncture_point('GB28','gallbladder',28,'Wei Dao','维道','Linking Path','front',135.0,204.0,true,'upper');
perform public.upsert_acupuncture_point('GB29','gallbladder',29,'Ju Liao','居髎','Squatting Bone-Hole','front',134.0,216.0,true,'lower');
perform public.upsert_acupuncture_point('GB30','gallbladder',30,'Huan Tiao','环跳','Jumping Round','back',132.0,234.0,true,'lower');
perform public.upsert_acupuncture_point('GB31','gallbladder',31,'Feng Shi','风市','Wind Market','front',132.0,276.0,true,'lower');
perform public.upsert_acupuncture_point('GB32','gallbladder',32,'Zhong Du','中渎','Central River','front',131.0,306.0,true,'lower');
perform public.upsert_acupuncture_point('GB33','gallbladder',33,'Xi Yang Guan','膝阳关','Knee Yang Joint','front',129.0,332.0,true,'lower');
perform public.upsert_acupuncture_point('GB34','gallbladder',34,'Yang Ling Quan','阳陵泉','Yang Mound Spring','front',129.0,352.0,true,'lower');
perform public.upsert_acupuncture_point('GB35','gallbladder',35,'Yang Jiao','阳交','Yang Intersection','front',129.0,376.0,true,'lower');
perform public.upsert_acupuncture_point('GB36','gallbladder',36,'Wai Qiu','外丘','Outer Mound','front',128.0,386.0,true,'lower');
perform public.upsert_acupuncture_point('GB37','gallbladder',37,'Guang Ming','光明','Bright Light','front',128.0,408.0,true,'lower');
perform public.upsert_acupuncture_point('GB38','gallbladder',38,'Yang Fu','阳辅','Yang Assistance','front',128.0,428.0,true,'lower');
perform public.upsert_acupuncture_point('GB39','gallbladder',39,'Xuan Zhong','悬钟','Suspended Bell','front',128.0,442.0,true,'lower');
perform public.upsert_acupuncture_point('GB40','gallbladder',40,'Qiu Xu','丘墟','Mound of Ruins','front',128.0,458.0,true,'lower');
perform public.upsert_acupuncture_point('GB41','gallbladder',41,'Zu Lin Qi','足临泣','Foot Overlooking Tears','front',127.0,474.0,true,'lower');
perform public.upsert_acupuncture_point('GB42','gallbladder',42,'Di Wu Hui','地五会','Earth Fivefold Convergence','front',127.0,482.0,true,'lower');
perform public.upsert_acupuncture_point('GB43','gallbladder',43,'Xia Xi','侠溪','Pinched Ravine','front',127.0,492.0,true,'lower');
perform public.upsert_acupuncture_point('GB44','gallbladder',44,'Zu Qiao Yin','足窍阴','Foot Portal Yin','front',127.0,500.0,true,'lower');
-- LR · liver
perform public.upsert_acupuncture_point('LR1','liver',1,'Da Dun','大敦','Large Pile','front',122.0,498.0,true,'lower');
perform public.upsert_acupuncture_point('LR2','liver',2,'Xing Jian','行间','Moving Between','front',118.7,468.8,true,'lower');
perform public.upsert_acupuncture_point('LR3','liver',3,'Tai Chong','太冲','Supreme Rush','front',115.1,439.7,true,'lower');
perform public.upsert_acupuncture_point('LR4','liver',4,'Zhong Feng','中封','Mound Centre','front',113.0,410.4,true,'lower');
perform public.upsert_acupuncture_point('LR5','liver',5,'Li Gou','蠡沟','Woodworm Canal','front',113.0,381.1,true,'lower');
perform public.upsert_acupuncture_point('LR6','liver',6,'Zhong Du','中都','Central Metropolis','front',113.8,351.8,true,'lower');
perform public.upsert_acupuncture_point('LR7','liver',7,'Xi Guan','膝关','Knee Joint','front',117.1,322.6,true,'lower');
perform public.upsert_acupuncture_point('LR8','liver',8,'Qu Quan','曲泉','Spring at the Bend','front',118.9,293.3,true,'lower');
perform public.upsert_acupuncture_point('LR9','liver',9,'Yin Bao','阴包','Yin Bladder','front',120.4,264.0,true,'lower');
perform public.upsert_acupuncture_point('LR10','liver',10,'Zu Wu Li','足五里','Leg Five Li','front',121.9,234.7,true,'lower');
perform public.upsert_acupuncture_point('LR11','liver',11,'Yin Lian','阴廉','Yin Corner','front',125.1,205.5,true,'lower');
perform public.upsert_acupuncture_point('LR12','liver',12,'Ji Mai','急脉','Urgent Pulse','front',128.9,176.4,true,'lower');
perform public.upsert_acupuncture_point('LR13','liver',13,'Zhang Men','章门','Camphorwood Gate','front',132.8,147.3,true,'upper');
perform public.upsert_acupuncture_point('LR14','liver',14,'Qi Men','期门','Cycle Gate','front',134.0,118.0,true,'upper');
-- REN · ren
perform public.upsert_acupuncture_point('REN1','ren',1,'Hui Yin','会阴','Meeting of Yin','front',100.0,214.0,false,'center');
perform public.upsert_acupuncture_point('REN2','ren',2,'Qu Gu','曲骨','Curved Bone','front',100.0,208.0,false,'center');
perform public.upsert_acupuncture_point('REN3','ren',3,'Zhong Ji','中极','Central Pole','front',100.0,196.0,false,'center');
perform public.upsert_acupuncture_point('REN4','ren',4,'Guan Yuan','关元','Origin Pass','front',100.0,190.0,false,'center');
perform public.upsert_acupuncture_point('REN5','ren',5,'Shi Men','石门','Stone Gate','front',100.0,184.0,false,'center');
perform public.upsert_acupuncture_point('REN6','ren',6,'Qi Hai','气海','Sea of Qi','front',100.0,180.0,false,'center');
perform public.upsert_acupuncture_point('REN7','ren',7,'Yin Jiao','阴交','Yin Intersection','front',100.0,176.0,false,'center');
perform public.upsert_acupuncture_point('REN8','ren',8,'Shen Que','神阙','Spirit Gate Tower','front',100.0,172.0,false,'center');
perform public.upsert_acupuncture_point('REN9','ren',9,'Shui Fen','水分','Water Divide','front',100.0,164.0,false,'center');
perform public.upsert_acupuncture_point('REN10','ren',10,'Xia Wan','下脘','Lower Venter','front',100.0,158.0,false,'center');
perform public.upsert_acupuncture_point('REN11','ren',11,'Jian Li','建里','Interior Strengthening','front',100.0,152.0,false,'center');
perform public.upsert_acupuncture_point('REN12','ren',12,'Zhong Wan','中脘','Central Venter','front',100.0,146.0,false,'center');
perform public.upsert_acupuncture_point('REN13','ren',13,'Shang Wan','上脘','Upper Venter','front',100.0,140.0,false,'center');
perform public.upsert_acupuncture_point('REN14','ren',14,'Ju Que','巨阙','Great Tower Gate','front',100.0,132.0,false,'center');
perform public.upsert_acupuncture_point('REN15','ren',15,'Jiu Wei','鸠尾','Turtledove Tail','front',100.0,126.0,false,'center');
perform public.upsert_acupuncture_point('REN16','ren',16,'Zhong Ting','中庭','Central Courtyard','front',100.0,118.0,false,'center');
perform public.upsert_acupuncture_point('REN17','ren',17,'Shan Zhong','膻中','Chest Centre','front',100.0,108.0,false,'center');
perform public.upsert_acupuncture_point('REN18','ren',18,'Yu Tang','玉堂','Jade Hall','front',100.0,100.0,false,'center');
perform public.upsert_acupuncture_point('REN19','ren',19,'Zi Gong','紫宫','Purple Palace','front',100.0,94.0,false,'center');
perform public.upsert_acupuncture_point('REN20','ren',20,'Hua Gai','华盖','Florid Canopy','front',100.0,88.0,false,'center');
perform public.upsert_acupuncture_point('REN21','ren',21,'Xuan Ji','璇玑','Jade Pivot','front',100.0,82.0,false,'center');
perform public.upsert_acupuncture_point('REN22','ren',22,'Tian Tu','天突','Celestial Chimney','front',100.0,76.0,false,'center');
perform public.upsert_acupuncture_point('REN23','ren',23,'Lian Quan','廉泉','Ridge Spring','front',100.0,66.0,false,'center');
perform public.upsert_acupuncture_point('REN24','ren',24,'Cheng Jiang','承浆','Sauce Receptacle','front',100.0,60.0,false,'center');
-- DU · du
perform public.upsert_acupuncture_point('DU1','du',1,'Chang Qiang','长强','Long Strong','back',100.0,238.0,false,'center');
perform public.upsert_acupuncture_point('DU2','du',2,'Yao Shu','腰俞','Lumbar Shu','back',100.0,230.0,false,'center');
perform public.upsert_acupuncture_point('DU3','du',3,'Yao Yang Guan','腰阳关','Lumbar Yang Pass','back',100.0,200.0,false,'center');
perform public.upsert_acupuncture_point('DU4','du',4,'Ming Men','命门','Life Gate','back',100.0,190.0,false,'center');
perform public.upsert_acupuncture_point('DU5','du',5,'Xuan Shu','悬枢','Suspended Pivot','back',100.0,182.0,false,'center');
perform public.upsert_acupuncture_point('DU6','du',6,'Ji Zhong','脊中','Spinal Centre','back',100.0,172.0,false,'center');
perform public.upsert_acupuncture_point('DU7','du',7,'Zhong Shu','中枢','Central Pivot','back',100.0,162.0,false,'center');
perform public.upsert_acupuncture_point('DU8','du',8,'Jin Suo','筋缩','Sinew Contraction','back',100.0,150.0,false,'center');
perform public.upsert_acupuncture_point('DU9','du',9,'Zhi Yang','至阳','Reaching Yang','back',100.0,138.0,false,'center');
perform public.upsert_acupuncture_point('DU10','du',10,'Ling Tai','灵台','Spirit Tower','back',100.0,130.0,false,'center');
perform public.upsert_acupuncture_point('DU11','du',11,'Shen Dao','神道','Spirit Pathway','back',100.0,122.0,false,'center');
perform public.upsert_acupuncture_point('DU12','du',12,'Shen Zhu','身柱','Body Pillar','back',100.0,112.0,false,'center');
perform public.upsert_acupuncture_point('DU13','du',13,'Tao Dao','陶道','Kiln Path','back',100.0,94.0,false,'center');
perform public.upsert_acupuncture_point('DU14','du',14,'Da Zhui','大椎','Great Hammer','back',100.0,84.0,false,'center');
perform public.upsert_acupuncture_point('DU15','du',15,'Ya Men','哑门','Mute Gate','back',100.0,74.0,false,'center');
perform public.upsert_acupuncture_point('DU16','du',16,'Feng Fu','风府','Wind Mansion','back',100.0,68.0,false,'center');
perform public.upsert_acupuncture_point('DU17','du',17,'Nao Hu','脑户','Brain Door','back',100.0,56.0,false,'center');
perform public.upsert_acupuncture_point('DU18','du',18,'Qiang Jian','强间','Unyielding Space','back',100.0,42.0,false,'center');
perform public.upsert_acupuncture_point('DU19','du',19,'Hou Ding','后顶','Behind the Vertex','back',100.0,30.0,false,'center');
perform public.upsert_acupuncture_point('DU20','du',20,'Bai Hui','百会','Hundred Convergences','back',100.0,20.0,false,'center');
perform public.upsert_acupuncture_point('DU21','du',21,'Qian Ding','前顶','Before the Vertex','front',100.0,22.0,false,'center');
perform public.upsert_acupuncture_point('DU22','du',22,'Xin Hui','囟会','Fontanel Meeting','front',100.0,26.0,false,'center');
perform public.upsert_acupuncture_point('DU23','du',23,'Shang Xing','上星','Upper Star','front',100.0,30.0,false,'center');
perform public.upsert_acupuncture_point('DU24','du',24,'Shen Ting','神庭','Spirit Court','front',100.0,34.0,false,'center');
perform public.upsert_acupuncture_point('DU25','du',25,'Su Liao','素髎','White Bone-Hole','front',100.0,46.0,false,'center');
perform public.upsert_acupuncture_point('DU26','du',26,'Shui Gou','水沟','Water Trough','front',100.0,51.0,false,'center');
perform public.upsert_acupuncture_point('DU27','du',27,'Dui Duan','兑端','Extremity of the Mouth','front',100.0,55.0,false,'center');
perform public.upsert_acupuncture_point('DU28','du',28,'Yin Jiao','龈交','Gum Intersection','front',100.0,58.0,false,'center');

end
$seed$;
