#!/usr/bin/env node
/**
 * The database's own description of itself, as TypeScript.
 *
 *   pnpm db:types            from the project (needs `npx supabase@latest login` once)
 *   pnpm db:types --local    from a local database (what CI runs, after the migrations)
 *
 * Writes packages/db/src/database.types.ts. packages/db/src/types.ts is written
 * by hand and has drifted: twelve tables are missing from it and a jsonb column
 * was typed as an array. The generated file is the database's word, and the
 * hand-written one is to be rebuilt on top of it rather than kept in step by eye.
 *
 * The project id is read from apps/web/.env.local (it is the host of the
 * Supabase address, not a secret). No key is read or needed: the command line
 * signs in with its own token.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'packages', 'db', 'src', 'database.types.ts');
const local = process.argv.includes('--local');

let source;
if (local) {
  source = ['--local'];
} else {
  let env = '';
  try {
    env = readFileSync(join(root, 'apps', 'web', '.env.local'), 'utf8');
  } catch {
    console.error('apps/web/.env.local is missing: the project address is read from it.');
    process.exit(1);
  }
  const url = /^NEXT_PUBLIC_SUPABASE_URL=["']?([^"'\r\n]+)/m.exec(env)?.[1] ?? '';
  const id = /^https:\/\/([a-z0-9]+)\.supabase\.co/.exec(url)?.[1];
  if (!id) {
    console.error('NEXT_PUBLIC_SUPABASE_URL in apps/web/.env.local is not a Supabase project address.');
    process.exit(1);
  }
  source = ['--project-id', id];
}

let types;
try {
  types = execFileSync(
    'npx',
    ['--yes', 'supabase@latest', 'gen', 'types', 'typescript', ...source, '--schema', 'public'],
    { encoding: 'utf8', shell: process.platform === 'win32', stdio: ['ignore', 'pipe', 'inherit'] },
  );
} catch {
  console.error(
    local
      ? 'Could not read the local database. Is it running (supabase db start)?'
      : 'Could not read the project. Sign in first:  npx supabase@latest login',
  );
  process.exit(1);
}
if (!/export type Database\b/.test(types)) {
  console.error('The answer does not look like a type file; nothing was written.');
  process.exit(1);
}

writeFileSync(
  out,
  `// Generated by \`pnpm db:types\` (scripts/db-types.mjs) — do not edit by hand.\n${types}`,
);
console.log(`Written: packages/db/src/database.types.ts (${types.split('\n').length} lines)`);
